#!/usr/bin/env python3
"""Exact checks for the a/b boundary contact-spectrum theorem.

The proof itself is the short homogeneous-centralizer argument recorded in
``current_context/AB_BOUNDARY_CONTACT_SPECTRUM.md``.  This verifier checks
the convention-sensitive identities and the finite homogeneous kernel
calculation used there.
"""

from __future__ import annotations

import sympy as sp


def bracket(left: sp.Expr, right: sp.Expr, z: sp.Symbol, w: sp.Symbol) -> sp.Expr:
    """The (z,w)-Jacobian convention used in the five-block equations."""

    return sp.expand(
        sp.diff(left, z) * sp.diff(right, w)
        - sp.diff(left, w) * sp.diff(right, z)
    )


def verify_leading_and_next_layers() -> None:
    z, w = sp.symbols("z w")
    alpha, beta, u, v = sp.symbols(
        "alpha beta u v", nonzero=True
    )
    p7_coefficients = sp.symbols("p70:3")

    root = w**3 * (u * w + v * z)
    p8 = alpha * root**2
    q12 = beta * root**3
    p7 = w**5 * sum(
        coefficient * z**index * w ** (2 - index)
        for index, coefficient in enumerate(p7_coefficients)
    )

    # The unique degree-eleven solution follows from the fact that the
    # homogeneous centralizer of root has no degree-eleven element.
    q11 = sp.expand(3 * beta * root * p7 / (2 * alpha))
    assert bracket(p8, q12, z, w) == 0
    assert (
        bracket(p8, q11, z, w) + bracket(p7, q12, z, w)
        == 0
    )

    ell = beta**2 / alpha**3
    difference23 = sp.expand(
        2 * q12 * q11 - 3 * ell * p8**2 * p7
    )
    assert difference23 == 0

    # This also audits the sign in the exact identity
    # {P,Q^2-LP^3}=2Q{P,Q}.
    P, Q, L = sp.symbols("P Q L")
    formal_identity = (
        sp.diff(P, P) * sp.diff(Q**2 - L * P**3, Q)
        - sp.diff(P, Q) * sp.diff(Q**2 - L * P**3, P)
    )
    assert formal_identity == 2 * Q


def verify_homogeneous_centralizer_spectrum() -> None:
    z, w = sp.symbols("z w")
    root = w**3 * (w + z)

    # Every high homogeneous part of Q^2-LP^3 has z-degree at most six.
    # The nonzero kernel of {root,-} occurs precisely in degrees divisible
    # by four, where it is generated by the corresponding power of root.
    for degree in range(8, 24):
        coefficients = sp.symbols(f"h{degree}_0:7")
        homogeneous = sum(
            coefficient * z**index * w ** (degree - index)
            for index, coefficient in enumerate(coefficients)
        )
        polynomial = sp.Poly(bracket(root, homogeneous, z, w), z, w)
        matrix, _ = sp.linear_eq_to_matrix(polynomial.coeffs(), coefficients)
        kernel = matrix.nullspace()

        if degree % 4:
            assert not kernel
            continue

        assert len(kernel) == 1
        power = sp.Poly(root ** (degree // 4), z, w)
        expected = sp.Matrix(
            [
                power.coeff_monomial(z**index * w ** (degree - index))
                for index in range(7)
            ]
        )
        assert expected != sp.zeros(7, 1)
        assert matrix * expected == sp.zeros(matrix.rows, 1)
        assert sp.Matrix.hstack(kernel[0], expected).rank() == 1


def verify_degree_ledger() -> None:
    # J=z^4/w^3 has total Laurent degree one.  Hence deg(2QJ)<=13.
    assert 4 - 3 == 1
    assert 12 + 1 == 13

    # If d is the top total degree of D, {P_8,D_d} has degree d+6.
    # It is therefore forced to vanish for d>7.
    assert all(degree + 6 > 13 for degree in range(8, 24))

    # D_24 is killed by the leading cusp ratio.  The centralizer spectrum
    # leaves exactly these possible nonzero top degrees above seven.
    assert [degree for degree in range(8, 24) if degree % 4 == 0] == [
        8,
        12,
        16,
        20,
    ]


def main() -> None:
    verify_leading_and_next_layers()
    verify_homogeneous_centralizer_spectrum()
    verify_degree_ledger()
    print("verified the leading and next homogeneous bracket identities")
    print("verified the degree 8..23 homogeneous centralizer spectrum")
    print("verified the total-degree and boundary-contact ledger")
    print("RESULT: ALL A/B CONTACT-SPECTRUM CHECKS PASS")


if __name__ == "__main__":
    main()
