#!/usr/bin/env python3
"""Audit the proposed global-monodromy shortcut for the radial Hamiltonians.

The degree-21 outer cover has

    R(w) = w*V(w)^2/U(w)^3.

Two tempting claims are:

1. triviality of the deck group should force a bounded two-end
   Hamiltonian with finite flow to vanish;
2. a trace-zero condition on the same two-end window should do so.

The first claim is false even inside the Lie algebra generated by the
seven radial modes.  The bracket of the low d=1 mode and the high d=4
mode is a nonzero Hamiltonian h(w).  In Darboux coordinates

    r=z^5/(5w), s=1/w, Omega=ds^dr,

its flow is a finite translation of r.  It fixes w, hence fixes every
outer cover R(w), regardless of the deck group.

The second claim is false as well.  This script computes field traces
on the complete degree-21 covers at the two rational F_32003 outer
points.  For 0<=j<=12 every Tr(w^j) is a constant.  Consequently

    w^j - Tr(w^j)/21,  1<=j<=12,

are twelve linearly independent, trace-zero polynomials with poles only
at infinity.  On the full scalar two-end window -1<=j<=12 the trace map
has rank only two.  This large kernel is the trace shadow of the
order-17 contact over the third branch value.

For each of the two rational degree-21 outer covers, the script builds
the actual high d=4 mode from the polynomial part of sqrt(wU/u_7).
Its bracket h(w) has degree at most four.  Since Tr(h) is constant,
subtracting Tr(h)/21 makes the Hamiltonian trace-zero without changing
its vector field.  This gives a countermodel satisfying bounded
principal parts, trace zero, finite flow, and exact preservation of the
Belyi cover simultaneously.
"""

from __future__ import annotations

import sympy as sp

from route_bd_fbar_obstruction import (
    K,
    PRIME,
    outer_coefficients,
)


def polynomial_product(
    left: list[int],
    right: list[int],
) -> list[int]:
    result = [0] * (len(left) + len(right) - 1)
    for i, a in enumerate(left):
        for j, b in enumerate(right):
            result[i + j] = (
                result[i + j] + a * b
            ) % PRIME
    return result


def rational_outer_polynomials(
    outer_parameter: int,
) -> tuple[list[int], list[int]]:
    u_ext, v_ext = outer_coefficients(K(outer_parameter))
    assert all(value.c1 == value.c2 == 0 for value in u_ext + v_ext)
    u = [value.c0 for value in u_ext]
    v = [value.c0 for value in v_ext]
    numerator = [0] + polynomial_product(v, v)
    denominator = polynomial_product(
        polynomial_product(u, u),
        u,
    )
    assert len(numerator) == len(denominator) == 22
    return numerator, denominator


def power_traces(
    outer_parameter: int,
) -> dict[int, object]:
    """Trace of w^j from F_p(w)/F_p(T), for -1<=j<=12."""

    target = sp.Symbol("target")
    fraction_field = sp.GF(PRIME).frac_field(target)
    numerator, denominator = rational_outer_polynomials(
        outer_parameter
    )
    coefficients = [
        fraction_field.from_sympy(a - target * b)
        for a, b in zip(numerator, denominator)
    ]
    degree = len(coefficients) - 1
    leading = coefficients[-1]
    assert leading
    monic = [coefficient / leading for coefficient in coefficients]

    traces: dict[int, object] = {
        -1: -coefficients[1] / coefficients[0],
        0: fraction_field.convert(degree),
    }
    for exponent in range(1, 13):
        value = fraction_field.zero
        for j in range(1, exponent):
            value += monic[degree - j] * traces[exponent - j]
        value += exponent * monic[degree - exponent]
        traces[exponent] = -value
    return traces


def evaluate_fraction(element: object, value: int) -> int | None:
    def evaluate_polynomial(polynomial: object) -> int:
        total = 0
        for (degree,), coefficient in polynomial.to_dict().items():
            total = (
                total
                + int(coefficient) * pow(value, degree, PRIME)
            ) % PRIME
        return total

    numerator = evaluate_polynomial(element.numer)
    denominator = evaluate_polynomial(element.denom)
    if not denominator:
        return None
    return numerator * pow(denominator, PRIME - 2, PRIME) % PRIME


def modular_rank(matrix: list[list[int]]) -> int:
    work = [row[:] for row in matrix]
    row_count = len(work)
    column_count = len(work[0]) if work else 0
    pivot_row = 0
    for column in range(column_count):
        pivot = next(
            (
                row
                for row in range(pivot_row, row_count)
                if work[row][column] % PRIME
            ),
            None,
        )
        if pivot is None:
            continue
        work[pivot_row], work[pivot] = work[pivot], work[pivot_row]
        inverse = pow(work[pivot_row][column], PRIME - 2, PRIME)
        work[pivot_row] = [
            entry * inverse % PRIME
            for entry in work[pivot_row]
        ]
        for row in range(row_count):
            if row == pivot_row:
                continue
            scalar = work[row][column] % PRIME
            if scalar:
                work[row] = [
                    (left - scalar * right) % PRIME
                    for left, right in zip(
                        work[row],
                        work[pivot_row],
                    )
                ]
        pivot_row += 1
        if pivot_row == row_count:
            break
    return pivot_row


def verify_trace_window_countermodels(outer_parameter: int) -> None:
    traces = power_traces(outer_parameter)
    exponents = tuple(range(-1, 13))
    rows: list[list[int]] = []
    for target_value in range(1, 200):
        row = [
            evaluate_fraction(traces[exponent], target_value)
            for exponent in exponents
        ]
        if any(value is None for value in row):
            continue
        rows.append([int(value) for value in row])
    assert modular_rank(rows) == 2

    positive_rows = [
        row[1:]
        for row in rows
    ]
    assert modular_rank(positive_rows) == 1

    trace_one = traces[0]
    assert trace_one == 21
    inverse_degree = pow(21, PRIME - 2, PRIME)
    for exponent in range(1, 13):
        trace_value = traces[exponent]
        # The trace is constant in the cover coordinate.
        assert trace_value.numer.degree() == 0
        assert trace_value.denom.degree() == 0
        center = trace_value * inverse_degree
        # Tr(w^j-center)=0.  The polynomial is nonzero because j>0.
        assert traces[exponent] - center * trace_one == 0


def verify_cover_fixed_finite_flow_countermodel() -> None:
    z, w, time = sp.symbols("z w time", nonzero=True)
    r_expression = z**5 / (5 * w)
    s_expression = 1 / w
    density = sp.det(
        sp.Matrix(
            [
                [sp.diff(s_expression, z), sp.diff(s_expression, w)],
                [sp.diff(r_expression, z), sp.diff(r_expression, w)],
            ]
        )
    )
    assert sp.simplify(density - z**4 / w**3) == 0

    # For k=1 the high d=4 scalar is C_4=w^2.  Formula (31) for
    # the bracket with the low d=1 scalar C_1=1 gives h=-5*w^2/4.
    high_d4 = w**2
    hamiltonian = sp.expand(
        sp.Rational(3, 4) * high_d4
        - w * sp.diff(high_d4, w)
    )
    assert hamiltonian == -sp.Rational(5, 4) * w**2

    r, s = sp.symbols("r s", nonzero=True)
    hamiltonian_s = hamiltonian.subs(w, 1 / s)
    r_new = sp.expand(r - time * sp.diff(hamiltonian_s, s))
    s_new = s
    assert r_new != r
    assert s_new == s
    # The time-t map is a finite Laurent translation in Darboux
    # coordinates.  It fixes w=1/s and therefore every R(w).
    assert sp.simplify(1 / s_new - 1 / s) == 0
    assert sp.diff(r_new, r) == 1


def verify_degree21_mode_countermodel(
    outer_parameter: int,
) -> None:
    traces = power_traces(outer_parameter)
    u_ext, _ = outer_coefficients(K(outer_parameter))
    assert all(value.c1 == value.c2 == 0 for value in u_ext)
    u = [value.c0 for value in u_ext]

    inverse_top = pow(u[7], PRIME - 2, PRIME)
    a7 = u[6] * inverse_top % PRIME
    a6 = u[5] * inverse_top % PRIME
    inverse_two = pow(2, PRIME - 2, PRIME)
    c4 = 1
    c3 = a7 * inverse_two % PRIME
    c2 = (a6 - c3 * c3) * inverse_two % PRIME
    high_d4 = {2: c2, 3: c3, 4: c4}
    assert high_d4[4]

    inverse_four = pow(4, PRIME - 2, PRIME)
    bracket_h = {
        degree: (
            (3 * inverse_four - degree)
            * coefficient
        ) % PRIME
        for degree, coefficient in high_d4.items()
    }
    assert bracket_h[4]

    trace_h = traces[0] * 0
    for degree, coefficient in bracket_h.items():
        trace_h += coefficient * traces[degree]
    assert trace_h.numer.degree() == 0
    assert trace_h.denom.degree() == 0

    center = trace_h / 21
    trace_centered_h = trace_h - center * traces[0]
    assert trace_centered_h == 0
    # The centering constant has zero Hamiltonian vector field, so the
    # nonzero finite r-translation generated by h is unchanged.


def main() -> None:
    verify_cover_fixed_finite_flow_countermodel()
    for outer_parameter in (26839, 16621):
        verify_trace_window_countermodels(outer_parameter)
        verify_degree21_mode_countermodel(outer_parameter)
    print("verified a nonzero cover-fixed finite Hamiltonian flow")
    print("verified twelve trace-zero two-end polynomial countermodels")
    print("verified full scalar trace-window rank is only two")
    print("verified trace-zero countermodels from the actual degree-21 modes")
    print("verified both rational degree-21 outer covers")


if __name__ == "__main__":
    main()
