#!/usr/bin/env python3
"""Exact affine Bezout certificates for the two case-c generic charts.

This deliberately does not use ``modStd``.  Singular's built-in
``liftstd`` computes a standard basis together with a transformation
matrix ``G = J*T``.  If a column of ``G`` is a nonzero constant, that
column of ``T`` gives an explicit Bezout identity.  The generated
certificate program then recomputes the dot product and requires it to
equal one as a polynomial over Q.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import pickle
import subprocess
import tempfile
import time

from route_bd_case_c_n3_generic_charts import (
    assert_reduced_shape,
    assert_variable_support,
    build_reduced_charts_from_imposed,
)
from route_bd_case_c_n3_hurwitz_bridge import (
    NVAR,
    ParameterPolynomial,
    QuotientElement,
)
from scratch_case_c_n3_generic_charts_Q import (
    DEFAULT_CACHE,
    minpoly_text,
    polynomial_text,
)


DEFAULT_OUTPUT = Path("tmp/case_c_n3_affine_lift_certificates")
CHOICES = {
    "L_NE_0": (0, 1),
    "L_EQ_0_A_NE_0": (0,),
}


def ring_text(free_variables: tuple[int, ...]) -> str:
    variables = ",".join(
        ("s", *(f"X{index}" for index in free_variables))
    )
    return f"ring R=0,({variables}),dp;\noption(redSB);"


def singular_string(path: Path) -> str:
    return str(path).replace("\\", "\\\\").replace('"', '\\"')


def certificate_program(
    chart_name: str,
    free_variables: tuple[int, ...],
    eliminant_text: str,
    rows_text: list[str],
    output_path: Path,
    algorithm: str,
    method: str,
) -> str:
    generators = ",\n".join((eliminant_text, *rows_text))
    ring = ring_text(free_variables)
    if method == "liftstd":
        construction = (
            "matrix T;",
            f'ideal G=liftstd(J,T,"{algorithm}");',
            "int unitcol=0;",
            "number unitcoeff=0;",
            "for (int col=1; col<=ncols(T); col++) {",
            "  if ((deg(G[col])==0) && (G[col]<>0)) {",
            "    unitcol=col;",
            "    unitcoeff=leadcoef(G[col]);",
            "    break;",
            "  }",
            "}",
            "if (unitcol==0) {",
            f'  print("FAIL {chart_name} NO_CONSTANT_STANDARD_BASIS_ELEMENT");',
            "  exit(2);",
            "}",
            "matrix C[nrows(T)][1];",
            "for (int row=1; row<=nrows(T); row++) {",
            "  C[row,1]=T[row,unitcol]/unitcoeff;",
            "}",
            f'print("CERTIFIED {chart_name} UNITCOL "+string(unitcol));',
        )
    else:
        construction = (
            "ideal One=1;",
            "matrix Units;",
            f'matrix C=lift(J,One,Units,"{algorithm}");',
            f'print("CERTIFIED {chart_name} DIRECT_LIFT");',
        )
    return "\n".join(
        (
            ring,
            f"ideal J=\n{generators};",
            *construction,
            "poly lhs=0;",
            "for (int row=1; row<=nrows(C); row++) {",
            "  lhs=lhs+J[row]*C[row,1];",
            "}",
            "poly residual=lhs-1;",
            "if (residual<>0) {",
            f'  print("FAIL {chart_name} NONZERO_EXACT_RESIDUAL");',
            "  residual;",
            "  exit(3);",
            "}",
            f'print("CERTIFIED {chart_name} GENERATORS "+string(size(J)));',
            f'print("CERTIFIED {chart_name} EXACT_RESIDUAL_ZERO");',
            # This is a standalone exact-Q witness: it stores the original
            # generators and the explicit coefficient column, followed by
            # an equality check that fails loudly if the identity is false.
            f'string out="{singular_string(output_path)}";',
            'write(out,"// Exact affine Bezout certificate generated by Singular");',
            f'write(out,"// Chart: {chart_name}");',
            f'write(out,"{ring.replace(chr(10), " ")}");',
            'write(out,"ideal J="+string(J)+";");',
            'write(out,"matrix C["+string(nrows(C))+"][1]="+string(C)+";");',
            'write(out,"poly residual=0;");',
            "for (row=1; row<=nrows(C); row++) {",
            '  write(out,"residual=residual+J["+string(row)+"]*C["'
            '+string(row)+",1];");',
            "}",
            'write(out,"residual=residual-1;");',
            'write(out,"if (residual<>0) { residual; exit(3); }");',
            f'write(out,"print(\\\"REPLAY CERTIFIED {chart_name} EXACT_RESIDUAL_ZERO\\\");");',
            "exit(0);",
        )
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--cache",
        type=Path,
        default=DEFAULT_CACHE,
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT,
    )
    parser.add_argument(
        "--chart",
        choices=tuple(CHOICES),
        action="append",
        help="chart to certify; repeat to select both (default: both)",
    )
    parser.add_argument(
        "--algorithm",
        choices=("std", "slimgb"),
        default="std",
    )
    parser.add_argument(
        "--method",
        choices=("lift", "liftstd"),
        default="lift",
        help="targeted membership lift is the default; liftstd is a crosscheck",
    )
    args = parser.parse_args()

    with args.cache.open("rb") as stream:
        cache = pickle.load(stream)
    _, eliminant, _, _ = cache["outer"]
    exact_imposed = cache["imposed"]
    QuotientElement.configure(eliminant)

    parameters = tuple(
        ParameterPolynomial.variable(index) for index in range(NVAR)
    )
    charts = build_reduced_charts_from_imposed(
        exact_imposed,
        parameters,
        QuotientElement.coerce(0),
        QuotientElement.coerce(1),
    )
    selected = set(args.chart or CHOICES)
    args.output_dir.mkdir(parents=True, exist_ok=True)

    for chart in charts:
        if chart.name not in selected:
            continue
        assert_variable_support(chart)
        assert_reduced_shape(chart)
        choice = CHOICES[chart.name]
        rows = list(chart.rows_by_weight[6]) + [
            chart.rows_by_weight[7][index] for index in choice
        ]
        certificate_path = (
            args.output_dir / f"{chart.name}_choice_{'_'.join(map(str, choice))}.sing"
        ).resolve()
        program = certificate_program(
            chart.name,
            chart.free_variables,
            minpoly_text(eliminant),
            [polynomial_text(row) for row in rows],
            certificate_path,
            args.algorithm,
            args.method,
        )
        print(
            f"starting {chart.name}: {len(rows) + 1} generators, "
            f"{len(chart.free_variables) + 1} variables, "
            f"{len(program)} input characters",
            flush=True,
        )
        start = time.monotonic()
        with tempfile.NamedTemporaryFile(
            mode="w",
            suffix=".sing",
            prefix="case_c_affine_lift_",
            delete=False,
        ) as stream:
            stream.write(program)
            input_path = Path(stream.name)
        try:
            result = subprocess.run(
                ["Singular", "-q", str(input_path)],
                text=True,
                capture_output=True,
                check=False,
            )
        finally:
            input_path.unlink(missing_ok=True)
        elapsed = time.monotonic() - start
        output = result.stdout + result.stderr
        print(output.strip(), flush=True)
        if result.returncode:
            raise RuntimeError(
                f"Singular failed for {chart.name} after {elapsed:.1f}s "
                f"(return code {result.returncode})"
            )
        marker = f"CERTIFIED {chart.name} EXACT_RESIDUAL_ZERO"
        if marker not in output:
            raise RuntimeError(
                f"missing exact certificate marker for {chart.name}"
            )
        print(
            f"wrote {certificate_path} in {elapsed:.1f}s "
            f"({certificate_path.stat().st_size} bytes)",
            flush=True,
        )

        replay_start = time.monotonic()
        replay = subprocess.run(
            ["Singular", "-q", str(certificate_path)],
            text=True,
            capture_output=True,
            check=False,
        )
        replay_elapsed = time.monotonic() - replay_start
        replay_output = replay.stdout + replay.stderr
        print(replay_output.strip(), flush=True)
        replay_marker = (
            f"REPLAY CERTIFIED {chart.name} EXACT_RESIDUAL_ZERO"
        )
        if replay.returncode or replay_marker not in replay_output:
            raise RuntimeError(
                f"standalone certificate replay failed for {chart.name}"
            )
        print(
            f"replayed {chart.name} exact identity in "
            f"{replay_elapsed:.1f}s",
            flush=True,
        )


if __name__ == "__main__":
    main()
