#!/usr/bin/env python3
"""Run the independent exact verification artifacts.

Invoke this file with the Python environment containing SymPy:

    .venv/bin/python verify_all.py
"""

from pathlib import Path
import subprocess
import sys


ROOT = Path(__file__).resolve().parent

SCRIPTS = [
    ROOT / "route_3d_cubic_pseudoplane_bridge.py",
    ROOT / "route_3d_cubic_pseudoplane_obstructions.py",
    ROOT / "route_3d_cubic_pseudoplane_etale_lift.py",
    ROOT / "route_a" / "verify_claims.py",
    ROOT / "route_a" / "nonhomogeneous_boundary.py",
    ROOT / "route_a" / "verify_triangular_hamiltonians.py",
    ROOT / "route_a" / "verify_monomial_cone.py",
    ROOT / "route_a" / "verify_w2_hensel_obstruction.py",
    ROOT / "route_a" / "verify_uv3_hensel_obstruction.py",
    ROOT / "route_a" / "verify_frobenius_family_obstruction.py",
    ROOT / "route_a" / "pfaff_global_structure.py",
    ROOT / "route_a" / "verify_dh_collision_architecture.py",
    ROOT / "route_a" / "verify_pfaff_homogeneous_obstruction.py",
    ROOT / "current_context" / "verify_route_a_quadratic_degree_exclusion.py",
    ROOT / "current_context" / "verify_route_a_cubic_branch_section_audit.py",
    ROOT / "current_context" / "verify_route_a_cubic_resolvent_s4_no_go.py",
    ROOT / "current_context" / "verify_route_a_unbranched_cubic_collision_audit.py",
    ROOT / "current_context" / "verify_route_a_line_collision_smooth_image_closure.py",
    ROOT / "current_context" / "verify_route_a_cubic_normalization_topology_audit.py",
    ROOT / "current_context" / "verify_route_a_local_class_group_link_no_go.py",
    ROOT / "current_context" / "verify_route_a_finite_flat_triple_non_gorenstein_audit.py",
    ROOT / "current_context" / "verify_route_a_non_gorenstein_gamma_d_incidence.py",
    ROOT / "current_context" / "verify_route_a_cubic_extreme_weight_valuation_audit.py",
    ROOT / "current_context" / "verify_route_a_cubic_dh_seed_linearization.py",
    ROOT / "current_context" / "verify_route_a_singular_dicritical_index_audit.py",
    ROOT / "current_context" / "verify_route_a_invariant_degree_filtration_sharpness.py",
    ROOT / "current_context" / "verify_route_a_residual_quadratic_infinity_audit.py",
    ROOT / "current_context" / "verify_route_a_global_monodromy_dicritical_bridge_no_go.py",
    ROOT / "current_context" / "verify_route_a_projective_intersection_bound_no_go.py",
    ROOT / "current_context" / "verify_route_a_canonical_infinity_tree_flexibility.py",
    ROOT / "current_context" / "verify_route_a_log_topology_cubic_collapse.py",
    ROOT / "current_context" / "verify_route_a_single_infinity_graph_no_go.py",
    ROOT / "current_context" / "verify_route_a_contractible_retained_sheet_cubic_exclusion.py",
    ROOT / "current_context" / "verify_route_a_degree_four_retained_sheet_audit.py",
    ROOT / "current_context" / "verify_route_a_degree_four_survivor_normalization_profile.py",
    ROOT / "current_context" / "verify_route_a_degree_four_log_adjunction_feasibility.py",
    ROOT / "route_a" / "equivariant_hensel.py",
    ROOT / "route_bd_verify.py",
    ROOT / "route_bd_ab_hurwitz_count.py",
    ROOT / "route_bd_fbar_obstruction.py",
    ROOT / "route_bd_universal_outer_edge.py",
    ROOT / "route_bd_universal_belyi_deck_rigidity.py",
    ROOT / "route_bd_universal_lattice_change.py",
    ROOT / "route_bd_universal_radial_kernel_theorem.py",
    ROOT / "route_bd_universal_hamiltonian_gauge.py",
    ROOT / "route_bd_universal_hamiltonian_filtration_limits.py",
    ROOT / "route_bd_universal_hamiltonian_endpoint_squares.py",
    ROOT / "route_bd_universal_contact_spectrum.py",
    ROOT / "route_bd_universal_osculating_cubic.py",
    ROOT / "route_bd_universal_depressed_wronskian.py",
    ROOT / "route_bd_universal_wronskian_countermodel.py",
    ROOT / "route_bd_fiveblock_discriminant_square.py",
    ROOT / "route_bd_allscale_marked_cusp_obstruction.py",
    ROOT / "current_context" / "verify_gghv_allscale_scope.py",
    ROOT / "current_context" / "verify_laurent_degree_descent.py",
    ROOT / "current_context" / "verify_toroidal_degree_descent_no_go.py",
    ROOT / "route_bd_transverse_34_local_countermodel.py",
    ROOT / "route_bd_osculating_leading_ode.py",
    ROOT / "route_bd_ab_osculating_delta4.py",
    ROOT / "route_bd_ab_delta4_nodal_obstruction.py",
    ROOT / "route_bd_ab_delta2_multisection_obstruction.py",
    ROOT / "route_bd_ab_delta1_cusp_jets.py",
    ROOT / "route_bd_ab_delta1_global_marked.py",
    ROOT / "route_bd_ab_delta1_tangent_cusp_obstruction.py",
    ROOT / "route_bd_ab_delta1_puiseux_chart_table.py",
    ROOT / "route_bd_ab_delta1_five_cell_global.py",
    ROOT / "route_bd_ab_delta1_35_wronskian.py",
    ROOT / "route_bd_ab_osculating_genus_budget.py",
    ROOT / "route_bd_belyi_hamiltonian_monodromy_audit.py",
    ROOT / "route_bd_radial_parahoric_geometry.py",
    ROOT / "route_bd_symplectic_bridge_countermodel.py",
    ROOT / "route_bd_integral_branch_rigidity.py",
    ROOT / "route_bd_radial_rational_descent_criterion.py",
    ROOT / "route_bd_radial_invariant_field_descent.py",
    ROOT / "current_context" / "verify_reciprocal_darboux_liouville.py",
    ROOT / "current_context" / "verify_global_darboux_divisor_section.py",
    ROOT / "current_context" / "verify_two_boundary_divisor_orbit.py",
    ROOT / "route_bd_radial_cusp_complement_audit.py",
    ROOT / "route_bd_asymptotic_curve_invariant.py",
    ROOT / "route_bd_rees_cusp_degeneration_audit.py",
    ROOT / "route_bd_case_c_cusp_pde_obstruction.py",
    ROOT / "route_bd_noncusp_difference_invariant.py",
    ROOT / "route_bd_ab_contact_spectrum.py",
    ROOT / "route_bd_gghv_transfer_chain_audit.py",
    ROOT / "route_bd_resonant_strata_audit.py",
    ROOT / "route_bd_universal_radial_rank.py",
    ROOT / "route_bd_universal_radial_consistency.py",
    ROOT / "route_bd_case_c_diagonal_hurwitz.py",
    ROOT / "route_bd_case_c_radial_obstruction.py",
    ROOT / "route_bd_case_c_toric_dicritical_reduction.py",
    ROOT / "route_bd_case_c_blocks.py",
    ROOT / "route_bd_case_c_graded.py",
    ROOT / "route_bd_case_c_next_descent.py",
    ROOT / "route_bd_case_c_approx_root.py",
    ROOT / "route_bd_case_c_approx_divisibility.py",
    ROOT / "route_bd_case_c_middle_divisibility_r0.py",
    ROOT / "route_bd_case_c_middle_divisibility_r1.py",
    ROOT / "route_bd_case_c_middle_divisibility_r2.py",
    ROOT / "route_bd_case_c_middle_divisibility_r3.py",
    ROOT / "route_bd_case_c_q10_chart_audit.py",
    ROOT / "route_bd_case_c_middle_divisibility.py",
    ROOT / "route_bd_case_c_constant_descent_r0.py",
    ROOT / "route_bd_case_c_constant_descent_r2.py",
    ROOT / "route_bd_case_c_constant_descent_r3.py",
    ROOT / "route_bd_case_c_constant_descent.py",
    ROOT / "route_bd_case_c_fractional_resonances_r0.py",
    ROOT / "route_bd_case_c_universal_fractional_resonances.py",
    ROOT / "route_bd_case_c_integral_normal_form.py",
    ROOT / "route_bd_case_c_integral_cokernel.py",
    ROOT / "route_bd_case_c_n3_hurwitz_bridge.py",
    ROOT / "route_bd_case_c_n3_generic_charts.py",
    ROOT / "current_context" / "verify_case_c_full_certificate_bridge.py",
    ROOT / "current_context" / "verify_case_c_cap_support_exhaustion_no_go.py",
    ROOT / "current_context" / "verify_cap_puiseux_euler_jet_invariant.py",
    ROOT / "current_context" / "verify_case_c_cap_resonant_star_no_go.py",
    ROOT / "current_context" / "verify_case_c_conormal_truncation_no_go.py",
    ROOT / "current_context" / "verify_case_c_outer_quartic_incidence_no_go.py",
    ROOT / "current_context" / "verify_case_c_outer_quartic_cokernel_no_go.py",
    ROOT / "current_context" / "verify_case_c_degree_four_incidence_audit.py",
    ROOT / "current_context" / "verify_case_c_outer_quartic_adjoint_no_go.py",
    ROOT / "current_context" / "verify_case_c_cokernel_nonlinear_pairing_no_go.py",
    ROOT / "current_context" / "verify_case_c_multistage_jet_staircase.py",
    ROOT / "route_bd_case_c_lower_remainder_identity.py",
    ROOT / "route_bd_case_c_formal_tail.py",
    ROOT / "route_bd_case_c_approx_pole_witness.py",
    ROOT / "route_c" / "verify_route_c.py",
    ROOT / "current_context" / "verify_3d_descent.py",
    ROOT / "current_context" / "verify_3d_coordinate_slice_orevkov_no_go.py",
    ROOT / "current_context" / "verify_weighted_lift_degree_six_graph_projection_no_go.py",
    ROOT / "current_context" / "verify_weighted_lift_first_nonlinear_cusp_subduction.py",
    ROOT / "current_context" / "verify_weighted_lift_second_subduction_ray_closure.py",
    ROOT / "current_context" / "verify_weighted_lift_mixed_linear_pivot_closure.py",
    ROOT / "current_context" / "verify_weighted_lift_all_quadratic_pivot_closure.py",
    ROOT / "current_context" / "verify_weighted_lift_c_divisible_cubic_face_closure.py",
    ROOT / "current_context" / "verify_weighted_lift_all_cubic_pivot_closure.py",
    ROOT / "current_context" / "verify_weighted_lift_all_quartic_pivot_closure.py",
    ROOT / "current_context" / "verify_weighted_lift_quadratic_cubic_lower_tier_correction_audit.py",
    ROOT / "current_context" / "verify_weighted_lift_all_quartic_pure_face_correction_audit.py",
    ROOT / "current_context" / "verify_weighted_lift_all_degree_binary_target_reduction.py",
    ROOT / "current_context" / "verify_weighted_lift_degree_six_exceptional_recurrence_closure.py",
    ROOT / "current_context" / "verify_weighted_lift_all_degree_d1_recurrence_closure.py",
    ROOT / "current_context" / "verify_weighted_lift_all_degree_d2_recurrence_closure.py",
    ROOT / "current_context" / "verify_weighted_lift_general_binary_first_lower_pole_obstruction.py",
    ROOT / "current_context" / "verify_weighted_lift_all_seed_x_sector_separation.py",
    ROOT / "current_context" / "verify_weighted_lift_all_degree_binary_target_closure.py",
    ROOT / "current_context" / "verify_weighted_lift_ternary_pure_boundary_separation_audit.py",
    ROOT / "current_context" / "verify_weighted_lift_degree_six_ternary_boundary_wronskian_closure.py",
    ROOT / "current_context" / "verify_weighted_lift_ternary_pure_full_boundary_closure.py",
    ROOT / "current_context" / "verify_weighted_lift_global_minimal_boundary_face_closure.py",
    ROOT / "current_context" / "verify_weighted_lift_nonhomogeneous_newton_vertex_closure.py",
    ROOT / "current_context" / "verify_weighted_lift_nonhomogeneous_degree_nine_cusp_closure.py",
    ROOT / "current_context" / "verify_weighted_lift_nonhomogeneous_degree_ten_newton_basis_closure.py",
    ROOT / "current_context" / "verify_weighted_lift_nonhomogeneous_degree_eleven_newton_basis_closure.py",
    ROOT / "current_context" / "verify_weighted_lift_sagbi_saturation_next_generator_audit.py",
    ROOT / "current_context" / "verify_weighted_lift_sagbi_after_w_markov_and_next_generators.py",
    ROOT / "current_context" / "verify_weighted_lift_cubic_graph_v_subduction_closure.py",
    ROOT / "current_context" / "search_fixed_source_plane.py",
    ROOT / "current_context" / "verify_fixed_source_plane_structure.py",
    ROOT / "current_context" / "verify_fixed_plane_conductor_normal_form.py",
    ROOT / "current_context" / "verify_fixed_plane_endpoint_blowup.py",
    ROOT / "current_context" / "verify_fixed_plane_endpoint_graded.py",
    ROOT / "current_context" / "verify_fixed_plane_formal_conductor_solution.py",
    ROOT / "current_context" / "verify_fixed_plane_liouville_form.py",
    ROOT / "current_context" / "verify_fixed_plane_rational_conductor_model.py",
    ROOT / "current_context" / "verify_fixed_plane_residue_lattice.py",
    ROOT / "current_context" / "verify_fixed_plane_residue_parity_scaling_no_go.py",
    ROOT / "current_context" / "verify_fixed_plane_second_endpoint.py",
    ROOT / "current_context" / "verify_fixed_plane_linked_cusp_semigroup.py",
    ROOT / "current_context" / "verify_fixed_plane_conductor_bockstein.py",
    ROOT / "current_context" / "verify_fixed_plane_conductor_filtration_image.py",
    ROOT / "current_context" / "verify_fixed_plane_global_conductor_image.py",
    ROOT / "current_context" / "verify_fixed_plane_conductor_arm_resolution.py",
    ROOT / "current_context" / "verify_fixed_plane_residual_oddness.py",
    ROOT / "current_context" / "verify_fixed_plane_residual_hamiltonian.py",
    ROOT / "current_context" / "verify_fixed_plane_linking_countermodel.py",
    ROOT / "current_context" / "verify_fixed_plane_residual_arm_entry.py",
    ROOT / "current_context" / "verify_fixed_plane_global_pullback_system.py",
    ROOT / "current_context" / "verify_fixed_plane_finality_cap_obstruction.py",
    ROOT / "current_context" / "verify_fixed_plane_defect_green_function.py",
    ROOT / "current_context" / "verify_fixed_plane_component_endpoint_pairing.py",
    ROOT / "current_context" / "verify_fixed_plane_normal_map_gluing.py",
    ROOT / "current_context" / "verify_fixed_plane_residue_exponent_classification.py",
    ROOT / "current_context" / "verify_fixed_plane_global_endpoint_normal_countermodel.py",
    ROOT / "current_context" / "verify_fixed_plane_sheet_loss_first_order_crt.py",
    ROOT / "current_context" / "verify_fixed_plane_all_order_hermite_crt_lift.py",
    ROOT / "current_context" / "verify_fixed_plane_critical_persistence_and_scalar_perturbation.py",
    ROOT / "current_context" / "verify_fixed_plane_projective_critical_scalar_rays.py",
    ROOT / "current_context" / "verify_fixed_plane_ab_boundary.py",
    ROOT / "current_context" / "verify_fixed_plane_affine_tail_critical.py",
    ROOT / "current_context" / "verify_fixed_plane_constant_tail_critical.py",
    ROOT / "current_context" / "verify_fixed_plane_homogeneous_square_tail_critical.py",
    ROOT / "current_context" / "verify_fixed_plane_homogeneous_quartic_square_tail_critical.py",
    ROOT / "current_context" / "verify_fixed_plane_quartic_affine_lower_critical.py",
    ROOT / "current_context" / "verify_fixed_plane_monomial_tail_critical.py",
    ROOT / "current_context" / "verify_fixed_plane_primitive_leading.py",
    ROOT / "current_context" / "verify_fixed_plane_quadratic_square_tail_critical.py",
    ROOT / "current_context" / "verify_fixed_plane_square_family.py",
    ROOT / "current_context" / "verify_fixed_plane_univariate_a_tail_critical.py",
    ROOT / "current_context" / "verify_fixed_plane_univariate_h_a_tail_critical.py",
    ROOT / "current_context" / "verify_fixed_plane_univariate_h_b_tail_critical.py",
    ROOT / "current_context" / "verify_fixed_plane_quadratic_pair.py",
    ROOT / "current_context" / "verify_fixed_plane_quadratic_cubic.py",
    ROOT / "current_context" / "verify_linear_sections.py",
    ROOT / "current_context" / "verify_triangular_sections.py",
    ROOT / "current_context" / "search_quadratic_triangular_graph.py",
    ROOT / "current_context" / "search_bounded_triangular_affine_graph.py",
    ROOT / "current_context" / "verify_all_linear_fibers.py",
    ROOT / "current_context" / "verify_factorization_plane.py",
    ROOT / "current_context" / "verify_general_factorization_plane.py",
    ROOT / "current_context" / "verify_no_triangular_pullback.py",
    ROOT / "current_context" / "verify_no_elementary_pullback.py",
    ROOT / "current_context" / "verify_no_constant_direction.py",
    ROOT / "current_context" / "verify_discriminant_fiber.py",
    ROOT / "current_context" / "verify_standard_system_weights.py",
    ROOT / "current_context" / "verify_standard_system_g_multiple_reparametrization_quotient.py",
    ROOT / "current_context" / "verify_standard_system_endpoint_pairing_branch_invisibility.py",
    ROOT / "current_context" / "verify_standard_system_endpoint_quotient_no_go.py",
    ROOT / "current_context" / "verify_standard_system_sylvester_remainder_correction_audit.py",
]


for script in SCRIPTS:
    command = [sys.executable, str(script)]
    if script.name == "equivariant_hensel.py":
        command.extend(["--stages", "12", "--max-degree", "120"])
    if script.name == "route_bd_fbar_obstruction.py":
        command.append("--run-singular")
    print(f"\n==> {script.relative_to(ROOT)}", flush=True)
    subprocess.run(command, cwd=ROOT, check=True)

print("\nall bundled exact verification scripts passed")
