#!/usr/bin/env python3
"""Run the independent exact verification artifacts.

Invoke this file with the Python environment containing SymPy:

    .venv/bin/python verify_all.py
"""

from pathlib import Path
import subprocess
import sys


ROOT = Path(__file__).resolve().parent

SCRIPTS = [
    ROOT / "route_3d_cubic_pseudoplane_bridge.py",
    ROOT / "route_3d_cubic_pseudoplane_obstructions.py",
    ROOT / "route_3d_cubic_pseudoplane_etale_lift.py",
    ROOT / "route_a" / "verify_claims.py",
    ROOT / "route_a" / "nonhomogeneous_boundary.py",
    ROOT / "route_a" / "verify_triangular_hamiltonians.py",
    ROOT / "route_a" / "verify_monomial_cone.py",
    ROOT / "route_a" / "verify_w2_hensel_obstruction.py",
    ROOT / "route_a" / "verify_uv3_hensel_obstruction.py",
    ROOT / "route_a" / "verify_frobenius_family_obstruction.py",
    ROOT / "route_a" / "pfaff_global_structure.py",
    ROOT / "route_a" / "verify_dh_collision_architecture.py",
    ROOT / "route_a" / "verify_pfaff_homogeneous_obstruction.py",
    ROOT / "route_a" / "equivariant_hensel.py",
    ROOT / "route_bd_verify.py",
    ROOT / "route_bd_ab_hurwitz_count.py",
    ROOT / "route_bd_fbar_obstruction.py",
    ROOT / "route_bd_universal_outer_edge.py",
    ROOT / "route_bd_universal_belyi_deck_rigidity.py",
    ROOT / "route_bd_universal_lattice_change.py",
    ROOT / "route_bd_universal_radial_kernel_theorem.py",
    ROOT / "route_bd_universal_hamiltonian_gauge.py",
    ROOT / "route_bd_universal_hamiltonian_filtration_limits.py",
    ROOT / "route_bd_universal_hamiltonian_endpoint_squares.py",
    ROOT / "route_bd_universal_contact_spectrum.py",
    ROOT / "route_bd_universal_osculating_cubic.py",
    ROOT / "route_bd_universal_depressed_wronskian.py",
    ROOT / "route_bd_universal_wronskian_countermodel.py",
    ROOT / "route_bd_fiveblock_discriminant_square.py",
    ROOT / "route_bd_allscale_marked_cusp_obstruction.py",
    ROOT / "current_context" / "verify_gghv_allscale_scope.py",
    ROOT / "route_bd_transverse_34_local_countermodel.py",
    ROOT / "route_bd_osculating_leading_ode.py",
    ROOT / "route_bd_ab_osculating_delta4.py",
    ROOT / "route_bd_ab_delta4_nodal_obstruction.py",
    ROOT / "route_bd_ab_delta2_multisection_obstruction.py",
    ROOT / "route_bd_ab_delta1_cusp_jets.py",
    ROOT / "route_bd_ab_delta1_global_marked.py",
    ROOT / "route_bd_ab_delta1_tangent_cusp_obstruction.py",
    ROOT / "route_bd_ab_delta1_puiseux_chart_table.py",
    ROOT / "route_bd_ab_delta1_five_cell_global.py",
    ROOT / "route_bd_ab_delta1_35_wronskian.py",
    ROOT / "route_bd_ab_osculating_genus_budget.py",
    ROOT / "route_bd_belyi_hamiltonian_monodromy_audit.py",
    ROOT / "route_bd_radial_parahoric_geometry.py",
    ROOT / "route_bd_symplectic_bridge_countermodel.py",
    ROOT / "route_bd_integral_branch_rigidity.py",
    ROOT / "route_bd_radial_rational_descent_criterion.py",
    ROOT / "route_bd_radial_invariant_field_descent.py",
    ROOT / "current_context" / "verify_reciprocal_darboux_liouville.py",
    ROOT / "route_bd_radial_cusp_complement_audit.py",
    ROOT / "route_bd_asymptotic_curve_invariant.py",
    ROOT / "route_bd_rees_cusp_degeneration_audit.py",
    ROOT / "route_bd_case_c_cusp_pde_obstruction.py",
    ROOT / "route_bd_noncusp_difference_invariant.py",
    ROOT / "route_bd_ab_contact_spectrum.py",
    ROOT / "route_bd_gghv_transfer_chain_audit.py",
    ROOT / "route_bd_resonant_strata_audit.py",
    ROOT / "route_bd_universal_radial_rank.py",
    ROOT / "route_bd_universal_radial_consistency.py",
    ROOT / "route_bd_case_c_diagonal_hurwitz.py",
    ROOT / "route_bd_case_c_radial_obstruction.py",
    ROOT / "route_bd_case_c_toric_dicritical_reduction.py",
    ROOT / "route_bd_case_c_blocks.py",
    ROOT / "route_bd_case_c_graded.py",
    ROOT / "route_bd_case_c_next_descent.py",
    ROOT / "route_bd_case_c_approx_root.py",
    ROOT / "route_bd_case_c_approx_divisibility.py",
    ROOT / "route_bd_case_c_middle_divisibility_r0.py",
    ROOT / "route_bd_case_c_middle_divisibility_r1.py",
    ROOT / "route_bd_case_c_middle_divisibility_r2.py",
    ROOT / "route_bd_case_c_middle_divisibility_r3.py",
    ROOT / "route_bd_case_c_q10_chart_audit.py",
    ROOT / "route_bd_case_c_middle_divisibility.py",
    ROOT / "route_bd_case_c_constant_descent_r0.py",
    ROOT / "route_bd_case_c_constant_descent_r2.py",
    ROOT / "route_bd_case_c_constant_descent_r3.py",
    ROOT / "route_bd_case_c_constant_descent.py",
    ROOT / "route_bd_case_c_fractional_resonances_r0.py",
    ROOT / "route_bd_case_c_universal_fractional_resonances.py",
    ROOT / "route_bd_case_c_integral_normal_form.py",
    ROOT / "route_bd_case_c_integral_cokernel.py",
    ROOT / "route_bd_case_c_n3_hurwitz_bridge.py",
    ROOT / "route_bd_case_c_n3_generic_charts.py",
    ROOT / "route_bd_case_c_lower_remainder_identity.py",
    ROOT / "route_bd_case_c_formal_tail.py",
    ROOT / "route_bd_case_c_approx_pole_witness.py",
    ROOT / "route_c" / "verify_route_c.py",
    ROOT / "current_context" / "verify_3d_descent.py",
    ROOT / "current_context" / "search_fixed_source_plane.py",
    ROOT / "current_context" / "verify_fixed_source_plane_structure.py",
    ROOT / "current_context" / "verify_fixed_plane_conductor_normal_form.py",
    ROOT / "current_context" / "verify_fixed_plane_endpoint_blowup.py",
    ROOT / "current_context" / "verify_fixed_plane_endpoint_graded.py",
    ROOT / "current_context" / "verify_fixed_plane_formal_conductor_solution.py",
    ROOT / "current_context" / "verify_fixed_plane_liouville_form.py",
    ROOT / "current_context" / "verify_fixed_plane_rational_conductor_model.py",
    ROOT / "current_context" / "verify_fixed_plane_residue_lattice.py",
    ROOT / "current_context" / "verify_fixed_plane_second_endpoint.py",
    ROOT / "current_context" / "verify_fixed_plane_linked_cusp_semigroup.py",
    ROOT / "current_context" / "verify_fixed_plane_conductor_bockstein.py",
    ROOT / "current_context" / "verify_fixed_plane_conductor_filtration_image.py",
    ROOT / "current_context" / "verify_fixed_plane_global_conductor_image.py",
    ROOT / "current_context" / "verify_fixed_plane_conductor_arm_resolution.py",
    ROOT / "current_context" / "verify_fixed_plane_residual_oddness.py",
    ROOT / "current_context" / "verify_fixed_plane_residual_hamiltonian.py",
    ROOT / "current_context" / "verify_fixed_plane_linking_countermodel.py",
    ROOT / "current_context" / "verify_fixed_plane_residual_arm_entry.py",
    ROOT / "current_context" / "verify_fixed_plane_global_pullback_system.py",
    ROOT / "current_context" / "verify_fixed_plane_ab_boundary.py",
    ROOT / "current_context" / "verify_fixed_plane_affine_tail_critical.py",
    ROOT / "current_context" / "verify_fixed_plane_constant_tail_critical.py",
    ROOT / "current_context" / "verify_fixed_plane_homogeneous_square_tail_critical.py",
    ROOT / "current_context" / "verify_fixed_plane_homogeneous_quartic_square_tail_critical.py",
    ROOT / "current_context" / "verify_fixed_plane_quartic_affine_lower_critical.py",
    ROOT / "current_context" / "verify_fixed_plane_monomial_tail_critical.py",
    ROOT / "current_context" / "verify_fixed_plane_primitive_leading.py",
    ROOT / "current_context" / "verify_fixed_plane_quadratic_square_tail_critical.py",
    ROOT / "current_context" / "verify_fixed_plane_square_family.py",
    ROOT / "current_context" / "verify_fixed_plane_univariate_a_tail_critical.py",
    ROOT / "current_context" / "verify_fixed_plane_univariate_h_a_tail_critical.py",
    ROOT / "current_context" / "verify_fixed_plane_univariate_h_b_tail_critical.py",
    ROOT / "current_context" / "verify_fixed_plane_quadratic_pair.py",
    ROOT / "current_context" / "verify_fixed_plane_quadratic_cubic.py",
    ROOT / "current_context" / "verify_linear_sections.py",
    ROOT / "current_context" / "verify_triangular_sections.py",
    ROOT / "current_context" / "search_quadratic_triangular_graph.py",
    ROOT / "current_context" / "search_bounded_triangular_affine_graph.py",
    ROOT / "current_context" / "verify_all_linear_fibers.py",
    ROOT / "current_context" / "verify_factorization_plane.py",
    ROOT / "current_context" / "verify_general_factorization_plane.py",
    ROOT / "current_context" / "verify_no_triangular_pullback.py",
    ROOT / "current_context" / "verify_no_elementary_pullback.py",
    ROOT / "current_context" / "verify_no_constant_direction.py",
    ROOT / "current_context" / "verify_discriminant_fiber.py",
    ROOT / "current_context" / "verify_standard_system_weights.py",
]


for script in SCRIPTS:
    command = [sys.executable, str(script)]
    if script.name == "equivariant_hensel.py":
        command.extend(["--stages", "12", "--max-degree", "120"])
    if script.name == "route_bd_fbar_obstruction.py":
        command.append("--run-singular")
    print(f"\n==> {script.relative_to(ROOT)}", flush=True)
    subprocess.run(command, cwd=ROOT, check=True)

print("\nall bundled exact verification scripts passed")
