// Incremental-SAT enumeration of a vertex-star fibre.
//
// This is an independent packing enumerator for the odd 63-orbit selector.
// The direct affine/profile routines are reused, but spanning-tree triples
// are generated by a lazy connectivity encoding rather than tree masks.

#define SIX_POINT_PARITY_NO_MAIN
#include "search_six_point_star_perpacking_parity.cpp"
#undef SIX_POINT_PARITY_NO_MAIN

#include <cadical.hpp>

namespace {

using WideMask = uint64_t;

bool is_tree_wide(const Graph& graph, WideMask mask) {
  if (__builtin_popcountll(mask) != graph.n - 1) return false;
  Dsu dsu(graph.n);
  for (int edge = 0; edge < graph.m(); ++edge) {
    if (!(mask & (WideMask{1} << edge))) continue;
    const auto [left, right] = graph.edges[edge];
    const int left_root = dsu.find(left);
    const int right_root = dsu.find(right);
    if (left_root == right_root) return false;
    dsu.parent[left_root] = right_root;
  }
  return true;
}

WideMask fundamental_completion_wide(
    const Graph& graph, WideMask tree) {
  std::vector<std::vector<std::pair<int, int>>> adjacency(graph.n);
  for (int edge = 0; edge < graph.m(); ++edge) {
    if (!(tree & (WideMask{1} << edge))) continue;
    const auto [left, right] = graph.edges[edge];
    adjacency[left].push_back({right, edge});
    adjacency[right].push_back({left, edge});
  }
  WideMask answer = 0;
  for (int chord = 0; chord < graph.m(); ++chord) {
    if (tree & (WideMask{1} << chord)) continue;
    const auto [start, finish] = graph.edges[chord];
    std::vector<int> previous_vertex(graph.n, -1);
    std::vector<int> previous_edge(graph.n, -1);
    std::vector<int> queue{start};
    previous_vertex[start] = start;
    for (std::size_t index = 0; index < queue.size(); ++index) {
      const int vertex = queue[index];
      if (vertex == finish) break;
      for (const auto [other, edge] : adjacency[vertex]) {
        if (previous_vertex[other] >= 0) continue;
        previous_vertex[other] = vertex;
        previous_edge[other] = edge;
        queue.push_back(other);
      }
    }
    assert(previous_vertex[finish] >= 0);
    WideMask circuit = WideMask{1} << chord;
    for (int vertex = finish; vertex != start;
         vertex = previous_vertex[vertex]) {
      circuit ^= WideMask{1} << previous_edge[vertex];
    }
    answer ^= circuit;
  }
  return answer;
}

DirectFlow direct_flow_from_wide_supports(
    const std::array<WideMask, 3>& supports, int edge_count) {
  DirectFlow flow{};
  for (int edge = 0; edge < edge_count; ++edge) {
    for (int bit = 0; bit < 3; ++bit) {
      flow[edge] |= static_cast<unsigned char>(
          ((supports[bit] >> edge) & 1U) << bit);
    }
  }
  return flow;
}

void print_wide_mask_array(const std::array<WideMask, 3>& values) {
  std::cout << '[' << values[0] << ',' << values[1] << ',' << values[2]
            << ']';
}

struct SatAttainment {
  DirectFlow flow{};
  std::array<WideMask, 3> supports{};
  std::array<WideMask, 3> trees{};
};

struct SatRootResult {
  bool feasible = false;
  bool has_odd = false;
  uint64_t models = 0;
  uint64_t odd_models = 0;
  uint64_t connectivity_cuts = 0;
  std::optional<SatAttainment> first_even;
  std::optional<SatAttainment> first_odd;
  int first_even_soluble = -1;
  int first_odd_soluble = -1;
  int first_odd_parallel = -1;
  int first_odd_skew = -1;
  int first_odd_coordinate_parallel = -1;
};

enum class Selector {
  TOTAL_ODD,
  PARALLEL_ODD,
  PARALLEL_ANY,
  COORDINATE_PARALLEL_ODD,
  COORDINATE_PARALLEL_ANY,
  SKEW_ODD,
  SKEW_ANY,
};

bool selected(const ParityProfile& profile, Selector selector) {
  switch (selector) {
    case Selector::TOTAL_ODD:
      return profile.soluble & 1;
    case Selector::PARALLEL_ODD:
      return profile.parallel_soluble & 1;
    case Selector::PARALLEL_ANY:
      return profile.parallel_soluble > 0;
    case Selector::COORDINATE_PARALLEL_ODD:
      return profile.coordinate_parallel_soluble & 1;
    case Selector::COORDINATE_PARALLEL_ANY:
      return profile.coordinate_parallel_soluble > 0;
    case Selector::SKEW_ODD:
      return profile.skew_soluble & 1;
    case Selector::SKEW_ANY:
      return profile.skew_soluble > 0;
  }
  assert(false);
  return false;
}

void add_clause(CaDiCaL::Solver& solver, const std::vector<int>& clause) {
  for (const int literal : clause) solver.add(literal);
  solver.add(0);
}

std::vector<int> component_without_root_tree_edges(
    const Graph& graph, WideMask tree) {
  std::vector<std::vector<int>> adjacency(graph.n);
  for (int edge = 0; edge < graph.m(); ++edge) {
    if (!(tree & (WideMask{1} << edge))) continue;
    const auto [left, right] = graph.edges[edge];
    adjacency[left].push_back(right);
    adjacency[right].push_back(left);
  }
  std::vector<int> reached(graph.n, false);
  std::vector<int> stack{0};
  reached[0] = true;
  while (!stack.empty()) {
    const int vertex = stack.back();
    stack.pop_back();
    for (const int other : adjacency[vertex]) {
      if (reached[other]) continue;
      reached[other] = true;
      stack.push_back(other);
    }
  }
  return reached;
}

SatRootResult search_root_sat(
    const Graph& graph, int root,
    std::unordered_map<std::string, ParityProfile>& profile_cache,
    const std::vector<int>* tait_colours = nullptr,
    bool exhaustive = false,
    Selector selector = Selector::TOTAL_ODD) {
  SatRootResult result;
  CaDiCaL::Solver solver;
  std::vector<int> outside_edges;
  std::array<int, MAX_M> outside_index{};
  outside_index.fill(-1);
  std::array<int, 3> root_edges{};
  for (int index = 0; index < 3; ++index) {
    root_edges[index] = graph.incidence[root][index];
  }
  std::sort(root_edges.begin(), root_edges.end());
  for (int edge = 0; edge < graph.m(); ++edge) {
    if (std::find(root_edges.begin(), root_edges.end(), edge) !=
        root_edges.end()) {
      continue;
    }
    outside_index[edge] = outside_edges.size();
    outside_edges.push_back(edge);
  }
  const auto variable = [&](int outside, int coordinate) {
    return 1 + 3 * outside + coordinate;
  };
  for (int outside = 0;
       outside < static_cast<int>(outside_edges.size()); ++outside) {
    add_clause(solver, {
        variable(outside, 0),
        variable(outside, 1),
        variable(outside, 2),
    });
    for (int first = 0; first < 3; ++first) {
      for (int second = first + 1; second < 3; ++second) {
        add_clause(solver, {
            -variable(outside, first),
            -variable(outside, second),
        });
      }
    }
  }
  if (tait_colours != nullptr) {
    for (int outside = 0;
         outside < static_cast<int>(outside_edges.size()); ++outside) {
      const int edge = outside_edges[outside];
      for (int coordinate = 0; coordinate < 3; ++coordinate) {
        if ((*tait_colours)[edge] ==
            (*tait_colours)[root_edges[coordinate]]) {
          // The omitted set for coordinate i must avoid colour i, so its
          // complementary tree contains the full corresponding matching.
          add_clause(solver, {-variable(outside, coordinate)});
        }
      }
    }
  }

  while (true) {
    const int status = solver.solve();
    if (status == 20) return result;
    assert(status == 10);
    std::array<WideMask, 3> trees{};
    for (int coordinate = 0; coordinate < 3; ++coordinate) {
      trees[coordinate] |= WideMask{1} << root_edges[coordinate];
    }
    for (int outside = 0;
         outside < static_cast<int>(outside_edges.size()); ++outside) {
      const int edge = outside_edges[outside];
      for (int coordinate = 0; coordinate < 3; ++coordinate) {
        // x[e,i] means that edge e is omitted by tree i.
        if (solver.val(variable(outside, coordinate)) < 0) {
          trees[coordinate] |= WideMask{1} << edge;
        }
      }
    }

    bool all_connected = true;
    for (int coordinate = 0; coordinate < 3; ++coordinate) {
      if (is_tree_wide(graph, trees[coordinate])) continue;
      const auto reached =
          component_without_root_tree_edges(graph, trees[coordinate]);
      if (std::all_of(
              reached.begin(), reached.end(),
              [](int value) { return value != 0; })) {
        // A connected coordinate may temporarily have too many edges.
        // Since the three omission sets partition E-delta(root), once all
        // three coordinates are connected their edge counts must all be
        // n-1, and they are trees.
        continue;
      }
      all_connected = false;
      std::vector<int> cut_clause;
      for (const int edge : outside_edges) {
        const auto [left, right] = graph.edges[edge];
        if (reached[left] == reached[right]) continue;
        cut_clause.push_back(
            -variable(outside_index[edge], coordinate));
      }
      // If the cut has no selectable outside edge, this coordinate can
      // never be connected and the whole fibre is infeasible.
      add_clause(solver, cut_clause);
      ++result.connectivity_cuts;
    }
    if (!all_connected) continue;

    result.feasible = true;
    ++result.models;
    std::array<WideMask, 3> supports{};
    for (int coordinate = 0; coordinate < 3; ++coordinate) {
      assert(is_tree_wide(graph, trees[coordinate]));
      supports[coordinate] =
          fundamental_completion_wide(graph, trees[coordinate]);
    }
    const DirectFlow flow =
        direct_flow_from_wide_supports(supports, graph.m());
    for (int edge = 0; edge < graph.m(); ++edge) {
      assert(direct_flow_value(flow, edge) != 0);
    }
    const DirectFlow canonical =
        canonical_direct_flow(flow, graph.m());
    const std::string key = direct_flow_key(canonical, graph.m());
    auto found = profile_cache.find(key);
    if (found == profile_cache.end()) {
      found = profile_cache.emplace(
          key, parity_profile(graph, canonical)).first;
    }
    const ParityProfile profile = found->second;
    const SatAttainment witness{flow, supports, trees};
    if (selected(profile, selector)) {
      result.has_odd = true;
      ++result.odd_models;
      if (!result.first_odd) {
        result.first_odd = witness;
        result.first_odd_soluble = profile.soluble;
        result.first_odd_parallel = profile.parallel_soluble;
        result.first_odd_skew = profile.skew_soluble;
        result.first_odd_coordinate_parallel =
            profile.coordinate_parallel_soluble;
      }
      if (!exhaustive) return result;
    }
    if (!selected(profile, selector) && !result.first_even) {
      result.first_even = witness;
      result.first_even_soluble = profile.soluble;
    }

    // Exclude this exact omission colouring.  Combined with the lazy cut
    // clauses, eventual UNSAT exhausts every star packing.
    std::vector<int> blocking_clause;
    for (int outside = 0;
         outside < static_cast<int>(outside_edges.size()); ++outside) {
      for (int coordinate = 0; coordinate < 3; ++coordinate) {
        if (solver.val(variable(outside, coordinate)) > 0) {
          blocking_clause.push_back(
              -variable(outside, coordinate));
          break;
        }
      }
    }
    add_clause(solver, blocking_clause);
  }
}

bool colour_edges_recursively(
    const Graph& graph, std::vector<int>& colours,
    std::vector<int>& used_at_vertex) {
  int chosen = -1;
  std::array<int, 3> options{};
  int option_count = 4;
  for (int edge = 0; edge < graph.m(); ++edge) {
    if (colours[edge] >= 0) continue;
    const auto [left, right] = graph.edges[edge];
    std::array<int, 3> candidate{};
    int count = 0;
    for (int colour = 0; colour < 3; ++colour) {
      if (!((used_at_vertex[left] | used_at_vertex[right]) &
            (1 << colour))) {
        candidate[count++] = colour;
      }
    }
    if (!count) return false;
    if (count < option_count) {
      chosen = edge;
      options = candidate;
      option_count = count;
    }
  }
  if (chosen < 0) return true;
  const auto [left, right] = graph.edges[chosen];
  for (int index = 0; index < option_count; ++index) {
    const int colour = options[index];
    colours[chosen] = colour;
    used_at_vertex[left] |= 1 << colour;
    used_at_vertex[right] |= 1 << colour;
    if (colour_edges_recursively(graph, colours, used_at_vertex)) {
      return true;
    }
    used_at_vertex[left] &= ~(1 << colour);
    used_at_vertex[right] &= ~(1 << colour);
    colours[chosen] = -1;
  }
  return false;
}

std::optional<std::vector<int>> tait_colouring(const Graph& graph) {
  std::vector<int> colours(graph.m(), -1);
  std::vector<int> used_at_vertex(graph.n, 0);
  const auto anchor = graph.incidence[0];
  for (int colour = 0; colour < 3; ++colour) {
    const int edge = anchor[colour];
    const auto [left, right] = graph.edges[edge];
    colours[edge] = colour;
    used_at_vertex[left] |= 1 << colour;
    used_at_vertex[right] |= 1 << colour;
  }
  if (!colour_edges_recursively(graph, colours, used_at_vertex)) {
    return std::nullopt;
  }
  return colours;
}

}  // namespace

int main(int argc, char** argv) {
  if (argc < 2 || argc > 3) {
    std::cerr
        << "usage: search_six_point_star_perpacking_parity_sat "
           "GRAPH6 [--tait-only|--exhaustive|--parallel-odd|"
           "--parallel-any|--coordinate-parallel-odd|"
           "--coordinate-parallel-any|--skew-odd|--skew-any]\n";
    return 64;
  }
  const std::string graph6 = argv[1];
  const Graph graph = parse_graph6(graph6);
  if (!is_cubic_connected(graph) || !is_bridgeless(graph)) return 3;
  const bool tait_only = argc == 3 && std::string(argv[2]) == "--tait-only";
  const bool exhaustive = argc == 3 && std::string(argv[2]) == "--exhaustive";
  Selector selector = Selector::TOTAL_ODD;
  if (argc == 3 && std::string(argv[2]) == "--parallel-odd") {
    selector = Selector::PARALLEL_ODD;
  } else if (argc == 3 && std::string(argv[2]) == "--parallel-any") {
    selector = Selector::PARALLEL_ANY;
  } else if (argc == 3 &&
             std::string(argv[2]) == "--coordinate-parallel-odd") {
    selector = Selector::COORDINATE_PARALLEL_ODD;
  } else if (argc == 3 &&
             std::string(argv[2]) == "--coordinate-parallel-any") {
    selector = Selector::COORDINATE_PARALLEL_ANY;
  } else if (argc == 3 && std::string(argv[2]) == "--skew-odd") {
    selector = Selector::SKEW_ODD;
  } else if (argc == 3 && std::string(argv[2]) == "--skew-any") {
    selector = Selector::SKEW_ANY;
  } else if (argc == 3 && !tait_only && !exhaustive) {
    return 64;
  }
  const auto colouring = tait_only ? tait_colouring(graph) : std::nullopt;
  if (tait_only && !colouring) {
    std::cout
        << "{\"schema\":\"tait-star-packing-sat-v1\","
        << "\"status\":\"NOT_TAIT_COLOURABLE\","
        << "\"graph6\":\"" << graph6 << "\""
        << ",\"vertices\":" << graph.n << "}\n";
    return 0;
  }

  std::unordered_map<std::string, ParityProfile> profile_cache;
  std::vector<SatRootResult> roots;
  int counter_root = -1;
  for (int root = 0; root < graph.n; ++root) {
    roots.push_back(search_root_sat(
        graph, root, profile_cache,
        tait_only ? &*colouring : nullptr, exhaustive, selector));
    if (roots.back().feasible && !roots.back().has_odd &&
        counter_root < 0) {
      counter_root = root;
    }
  }

  std::cout
      << "{\"schema\":\""
      << (tait_only ? "tait-star-packing-sat-v1"
                    : "six-point-star-perpacking-parity-sat-v1")
      << "\","
      << "\"status\":\""
      << (counter_root >= 0 ? "COUNTERMODEL" : "GRAPH_PASS")
      << "\",\"graph6\":\"" << graph6 << "\""
      << ",\"vertices\":" << graph.n
      << ",\"edges\":" << graph.m()
      << ",\"evaluated_flow_gl_orbits\":" << profile_cache.size()
      << ",\"selector\":\""
      << (selector == Selector::TOTAL_ODD ? "total-odd" :
          selector == Selector::PARALLEL_ODD ? "parallel-odd" :
          selector == Selector::PARALLEL_ANY ? "parallel-any" :
          selector == Selector::COORDINATE_PARALLEL_ODD ?
              "coordinate-parallel-odd" :
          selector == Selector::COORDINATE_PARALLEL_ANY ?
              "coordinate-parallel-any" :
          selector == Selector::SKEW_ODD ? "skew-odd" : "skew-any")
      << "\""
      << ",\"roots\":[";
  for (int root = 0; root < graph.n; ++root) {
    if (root) std::cout << ',';
    const auto& row = roots[root];
    std::cout
        << "{\"root\":" << root
        << ",\"feasible\":" << (row.feasible ? "true" : "false")
        << ",\"has_odd_packing\":"
        << (row.has_odd ? "true" : "false")
        << ",\"packing_models\":" << row.models
        << ",\"odd_packing_models\":" << row.odd_models
        << ",\"odd_packing_model_parity\":" << (row.odd_models & 1)
        << ",\"connectivity_cuts\":" << row.connectivity_cuts;
    if (row.first_odd) {
      std::cout
          << ",\"odd_witness\":{\"soluble_orbits\":"
          << row.first_odd_soluble
          << ",\"parallel_soluble_orbits\":"
          << row.first_odd_parallel
          << ",\"coordinate_parallel_soluble_orbits\":"
          << row.first_odd_coordinate_parallel
          << ",\"skew_soluble_orbits\":"
          << row.first_odd_skew
          << ",\"tree_masks\":";
      print_wide_mask_array(row.first_odd->trees);
      std::cout << ",\"completion_masks\":";
      print_wide_mask_array(row.first_odd->supports);
      std::cout << ",\"flow\":";
      print_direct_flow_word(graph, row.first_odd->flow);
      std::cout << '}';
    }
    if (row.first_even) {
      std::cout
          << ",\"even_control\":{\"soluble_orbits\":"
          << row.first_even_soluble << ",\"tree_masks\":";
      print_wide_mask_array(row.first_even->trees);
      std::cout << ",\"completion_masks\":";
      print_wide_mask_array(row.first_even->supports);
      std::cout << ",\"flow\":";
      print_direct_flow_word(graph, row.first_even->flow);
      std::cout << '}';
    }
    std::cout << '}';
  }
  std::cout << ']';
  if (counter_root >= 0) {
    std::cout << ",\"counterexample_root\":" << counter_root;
  }
  std::cout
      << ",\"scope\":\"SAT enumerates the realizable star fibre; an "
         "all-even result refutes only the per-packing selector, not "
         "FiveCDC.\"}\n";
  return counter_root >= 0 ? 2 : 0;
}
