#!/usr/bin/env python3
"""Audit a conditional rooted Kempe-reconfiguration lemma for D5 flows.

For each connected simple cubic graph supplied in graph6 format:

* enumerate every D5 flow, modulo the global S5 action;
* build exact Kempe orbits generated by transposing i,j on one connected
  component of the bichromatic even subgraph Y_ij at a time; and
* test whether, from every orbit, every unordered root-edge pair can be
  put on one component of some Y_ij.

This is an exploratory finite audit.  A negative row is a literal,
human-replayable countermodel to the conditional reconfiguration lemma,
not to FiveCDC: the displayed graph already has a D5 flow.
"""

from __future__ import annotations

import argparse
import itertools
import json
import sys
from collections import deque
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from tools.fixed_fano_merge_frontier import graph_from_graph6
from tools.flow_switch_audit import connected_components, is_bridgeless


LABELS = tuple(
    (1 << first) | (1 << second)
    for first, second in itertools.combinations(range(5), 2)
)
LABEL_SET = frozenset(LABELS)
PAIRS = tuple(itertools.combinations(range(5), 2))
PERMUTATIONS = tuple(itertools.permutations(range(5)))


def permute_label(label: int, permutation: tuple[int, ...]) -> int:
    answer = 0
    for coordinate in range(5):
        if (label >> coordinate) & 1:
            answer |= 1 << permutation[coordinate]
    return answer


PERMUTED_LABEL = {
    permutation: {
        label: permute_label(label, permutation)
        for label in LABELS
    }
    for permutation in PERMUTATIONS
}


def canonical(state: tuple[int, ...]) -> tuple[int, ...]:
    return min(
        tuple(PERMUTED_LABEL[permutation][label] for label in state)
        for permutation in PERMUTATIONS
    )


def enumerate_flows(graph) -> set[tuple[int, ...]]:
    incidence = [[] for _ in range(graph.vertices)]
    for edge, (left, right) in enumerate(graph.edges):
        incidence[left].append(edge)
        incidence[right].append(edge)
    assert all(len(row) == 3 for row in incidence)

    state = [0] * graph.edge_count
    answers: set[tuple[int, ...]] = set()

    def assign(edge: int, label: int, trail: list[int]) -> bool:
        if state[edge]:
            return state[edge] == label
        if label not in LABEL_SET:
            return False
        state[edge] = label
        trail.append(edge)
        queue = list(graph.edges[edge])
        while queue:
            vertex = queue.pop()
            row = incidence[vertex]
            assigned = [item for item in row if state[item]]
            if len(assigned) < 2:
                continue
            if len(assigned) == 3:
                if state[row[0]] ^ state[row[1]] ^ state[row[2]]:
                    return False
                continue
            missing = next(item for item in row if not state[item])
            forced = state[assigned[0]] ^ state[assigned[1]]
            if forced not in LABEL_SET:
                return False
            state[missing] = forced
            trail.append(missing)
            queue.extend(graph.edges[missing])
        return True

    def visit() -> None:
        try:
            edge = next(index for index, label in enumerate(state) if not label)
        except StopIteration:
            answers.add(canonical(tuple(state)))
            return

        # Fix the first unassigned edge to 01 only when the state is empty.
        # Every global S5 orbit has such a representative.
        choices = (LABELS[0],) if not any(state) else LABELS
        for label in choices:
            trail: list[int] = []
            if assign(edge, label, trail):
                visit()
            for changed in reversed(trail):
                state[changed] = 0

    visit()
    return answers


def active_mask(state: tuple[int, ...], first: int, second: int) -> int:
    return sum(
        1 << edge
        for edge, label in enumerate(state)
        if ((label >> first) & 1) ^ ((label >> second) & 1)
    )


def component_edge_masks(graph, mask: int) -> tuple[int, ...]:
    answer = []
    for component in connected_components(
        graph,
        (edge for edge in range(graph.edge_count) if (mask >> edge) & 1),
    ):
        component_mask = sum(
            1 << edge
            for edge, (left, right) in enumerate(graph.edges)
            if ((mask >> edge) & 1)
            and left in component
            and right in component
        )
        answer.append(component_mask)
    return tuple(answer)


def transpose_label(label: int, first: int, second: int) -> int:
    first_bit = (label >> first) & 1
    second_bit = (label >> second) & 1
    if first_bit == second_bit:
        return label
    return label ^ (1 << first) ^ (1 << second)


def neighbours(graph, state: tuple[int, ...]):
    for first, second in PAIRS:
        mask = active_mask(state, first, second)
        for component_mask in component_edge_masks(graph, mask):
            switched = tuple(
                transpose_label(label, first, second)
                if (component_mask >> edge) & 1
                else label
                for edge, label in enumerate(state)
            )
            yield canonical(switched)


def successful_root_pairs(graph, state: tuple[int, ...]) -> set[tuple[int, int]]:
    answer: set[tuple[int, int]] = set()
    for first, second in PAIRS:
        mask = active_mask(state, first, second)
        for component_mask in component_edge_masks(graph, mask):
            edges = [
                edge
                for edge in range(graph.edge_count)
                if (component_mask >> edge) & 1
            ]
            answer.update(itertools.combinations(edges, 2))
    return answer


def audit_graph(record: str) -> dict[str, object]:
    graph = graph_from_graph6(record)
    assert is_bridgeless(graph)
    all_flows = enumerate_flows(graph)
    unseen = set(all_flows)
    all_root_pairs = set(itertools.combinations(range(graph.edge_count), 2))
    orbits = []
    first_failure = None
    while unseen:
        initial = next(iter(unseen))
        orbit = {initial}
        queue = deque([initial])
        successes: set[tuple[int, int]] = set()
        while queue:
            state = queue.popleft()
            successes.update(successful_root_pairs(graph, state))
            for neighbour in neighbours(graph, state):
                assert neighbour in all_flows
                if neighbour not in orbit:
                    orbit.add(neighbour)
                    queue.append(neighbour)
        unseen.difference_update(orbit)
        failures = sorted(all_root_pairs - successes)
        row = {
            "states_mod_global_s5": len(orbit),
            "root_pairs_rescued": len(successes),
            "root_pairs_failed": len(failures),
        }
        orbits.append(row)
        if failures and first_failure is None:
            root_first, root_second = failures[0]
            first_failure = {
                "initial_labels_hex": [hex(label) for label in initial],
                "root_edge_indices": [root_first, root_second],
                "root_edges": [
                    list(graph.edges[root_first]),
                    list(graph.edges[root_second]),
                ],
                "orbit": row,
            }
    return {
        "graph6": record,
        "vertices": graph.vertices,
        "edges": graph.edge_count,
        "d5_flows_mod_global_s5": len(all_flows),
        "kempe_orbits_mod_global_s5": len(orbits),
        "all_orbits_rescue_all_root_pairs": first_failure is None,
        "first_failure": first_failure,
        "orbit_summaries": orbits,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("graph6_file", type=Path)
    parser.add_argument("--output", type=Path)
    arguments = parser.parse_args()
    records = [
        line.strip()
        for line in arguments.graph6_file.read_text(encoding="ascii").splitlines()
        if line.strip()
    ]
    report = {
        "schema": "d5-root-kempe-orbit-audit-v1",
        "claim_tested": (
            "Every Kempe orbit of D5 flows rescues every unordered root-edge "
            "pair onto one component of some Y_ij."
        ),
        "graphs": [audit_graph(record) for record in records],
    }
    text = json.dumps(report, indent=2, sort_keys=True) + "\n"
    if arguments.output:
        arguments.output.write_text(text, encoding="utf-8")
    else:
        print(text, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
