#!/usr/bin/env python3
"""Exact audits for the D5 open-ear boundary operator.

The value set B is the ten weight-two vectors in F_2^5.  A boundary word
is valid when its xor is zero.  This script verifies:

* the exact operator induced by an open ear with m internal vertices;
* its local row/column multiplicities for 0 <= m <= 5;
* a 46-orbit/4620-word abstract relation with full two-coordinate
  projections, all twelve C5-cap intersections, and elementary
  bichromatic-switch closure, whose one-vertex-ear image has only
  5 orbits/370 words; this is a countermodel to coarse invariant
  inductions, not a graph-realizable counterexample;
* the complete seven-state semigroup generated by repeatedly adding
  two-internal-vertex ears to the five-cycle pole; and
* optionally, the finite semigroup generated by ears with 1, 2, or 3
  internal vertices while the boundary size remains in {4,5,6}.

Nothing here proves or disproves FiveCDC or the universal 46-orbit
five-pole conjecture.  The code uses only the Python standard library.
"""

from __future__ import annotations

import argparse
from collections import Counter, defaultdict
from functools import lru_cache, reduce
from itertools import combinations, permutations, product
import json
import math


COLORS = range(5)
B = tuple(
    sum(1 << color for color in pair)
    for pair in combinations(COLORS, 2)
)
B_SET = frozenset(B)
COLOR_PERMUTATIONS = tuple(permutations(COLORS))


def xor_sum(values: tuple[int, ...]) -> int:
    return reduce(int.__xor__, values, 0)


@lru_cache(maxsize=None)
def permute_value(value: int, permutation: tuple[int, ...]) -> int:
    return sum(
        1 << permutation[color]
        for color in COLORS
        if value >> color & 1
    )


@lru_cache(maxsize=None)
def color_representative(word: tuple[int, ...]) -> tuple[int, ...]:
    return min(
        tuple(permute_value(value, permutation) for value in word)
        for permutation in COLOR_PERMUTATIONS
    )


@lru_cache(maxsize=None)
def valid_words(terminals: int) -> tuple[tuple[int, ...], ...]:
    answer = []
    for prefix in product(B, repeat=terminals - 1):
        last = xor_sum(prefix)
        if last in B_SET:
            answer.append((*prefix, last))
    return tuple(answer)


@lru_cache(maxsize=None)
def orbit_representatives(terminals: int) -> tuple[tuple[int, ...], ...]:
    return tuple(sorted({
        color_representative(word) for word in valid_words(terminals)
    }))


@lru_cache(maxsize=None)
def orbit_words(
    terminals: int,
) -> dict[tuple[int, ...], tuple[tuple[int, ...], ...]]:
    grouped: dict[tuple[int, ...], list[tuple[int, ...]]] = defaultdict(list)
    for word in valid_words(terminals):
        grouped[color_representative(word)].append(word)
    return {
        representative: tuple(words)
        for representative, words in grouped.items()
    }


def cap_extension_count(boundary: tuple[int, ...]) -> int:
    count = 0
    for start in B:
        current = start
        valid = True
        for value in boundary:
            current ^= value
            if current not in B_SET:
                valid = False
                break
        if valid:
            assert current == start
            count += 1
    return count


@lru_cache(maxsize=None)
def cycle_relation(terminals: int) -> frozenset[tuple[int, ...]]:
    return frozenset(
        word for word in valid_words(terminals)
        if cap_extension_count(word)
    )


@lru_cache(maxsize=None)
def ear_boundaries(
    left: int, right: int, internal_vertices: int
) -> tuple[tuple[int, ...], ...]:
    """Boundary words produced along an ear with fixed endpoint values.

    If the successive ear-edge values are y_0,...,y_m, the new semiedge
    value at internal vertex i is z_i=y_{i-1} xor y_i.  Every y_i and z_i
    must lie in B.
    """
    if internal_vertices == 0:
        return ((),) if left == right else ()
    answer: list[tuple[int, ...]] = []

    def search(
        index: int, current: int, boundary: list[int]
    ) -> None:
        if index == internal_vertices:
            if current == right:
                answer.append(tuple(boundary))
            return
        for following in B:
            new_boundary = current ^ following
            if new_boundary not in B_SET:
                continue
            boundary.append(new_boundary)
            search(index + 1, following, boundary)
            boundary.pop()

    search(0, left, [])
    return tuple(answer)


def add_ear(
    relation: frozenset[tuple[int, ...]],
    left_position: int,
    right_position: int,
    internal_vertices: int,
) -> frozenset[tuple[int, ...]]:
    terminals = len(next(iter(relation)))
    retained = tuple(
        position for position in range(terminals)
        if position not in (left_position, right_position)
    )
    answer = set()
    for word in relation:
        prefix = tuple(word[position] for position in retained)
        for new_boundary in ear_boundaries(
            word[left_position],
            word[right_position],
            internal_vertices,
        ):
            answer.add(prefix + new_boundary)
    return frozenset(answer)


def relation_orbits(
    relation: frozenset[tuple[int, ...]]
) -> frozenset[tuple[int, ...]]:
    return frozenset(color_representative(word) for word in relation)


def local_kernel_profiles() -> dict[str, object]:
    report = {}
    for internal_vertices in range(6):
        rows: dict[tuple[int, int], set[tuple[int, ...]]] = defaultdict(set)
        columns: dict[tuple[int, ...], set[tuple[int, int]]] = defaultdict(set)
        for left in B:
            for right in B:
                for boundary in ear_boundaries(
                    left, right, internal_vertices
                ):
                    rows[left, right].add(boundary)
                    columns[boundary].add((left, right))
        report[str(internal_vertices)] = {
            "supported_input_pairs_by_xor_weight": dict(sorted(Counter(
                (left ^ right).bit_count() for left, right in rows
            ).items())),
            "row_degree_profile": dict(sorted(Counter(
                len(boundaries) for boundaries in rows.values()
            ).items())),
            "outputs_by_total_xor_weight": dict(sorted(Counter(
                xor_sum(boundary).bit_count() for boundary in columns
            ).items())),
            "column_degree_profile": dict(sorted(Counter(
                len(inputs) for inputs in columns.values()
            ).items())),
        }
    return report


def e1_output_representative(
    word: tuple[int, ...], left: int = 0, right: int = 1
) -> tuple[int, ...] | None:
    new_value = word[left] ^ word[right]
    if new_value not in B_SET:
        return None
    retained = tuple(
        word[position] for position in range(len(word))
        if position not in (left, right)
    )
    return color_representative(retained + (new_value,))


def toggle(
    word: tuple[int, ...],
    positions: tuple[int, ...],
    color_pair: int,
) -> tuple[int, ...]:
    output = list(word)
    for position in positions:
        output[position] ^= color_pair
    answer = tuple(output)
    assert all(value in B_SET for value in answer)
    assert xor_sum(answer) == 0
    return answer


def elementary_switching_closed(
    states: set[tuple[int, ...]],
) -> bool:
    """The elementary single-bichromatic-pair test used by the C5 audit."""
    expanded = {
        tuple(
            permute_value(value, permutation) for value in representative
        )
        for representative in states
        for permutation in COLOR_PERMUTATIONS
    }
    for word in expanded:
        for left_color, right_color in combinations(COLORS, 2):
            pair = (1 << left_color) | (1 << right_color)
            positions = tuple(
                position
                for position, value in enumerate(word)
                if bool(value & (1 << left_color))
                ^ bool(value & (1 << right_color))
            )
            assert len(positions) in (0, 2, 4)
            if len(positions) == 2:
                if color_representative(
                    toggle(word, positions, pair)
                ) not in states:
                    return False
            elif len(positions) == 4:
                if color_representative(
                    toggle(word, positions, pair)
                ) not in states:
                    return False
                first, second, third, fourth = positions
                pairings = (
                    ((first, second), (third, fourth)),
                    ((first, third), (second, fourth)),
                    ((first, fourth), (second, third)),
                )
                if not any(
                    all(
                        color_representative(
                            toggle(word, endpoint_pair, pair)
                        ) in states
                        for endpoint_pair in pairing
                    )
                    for pairing in pairings
                ):
                    return False
    return True


def five_cycle_cap_orbit_sets() -> tuple[frozenset[tuple[int, ...]], ...]:
    cyclic_orders = tuple(
        (0, *tail)
        for tail in permutations((1, 2, 3, 4))
        if tail[0] < tail[-1]
    )
    result = []
    for order in cyclic_orders:
        result.append(frozenset(
            color_representative(word)
            for word in valid_words(5)
            if cap_extension_count(tuple(word[position] for position in order))
        ))
    assert len(result) == 12
    assert all(len(cap) == 46 for cap in result)
    return tuple(result)


def abstract_scalar_countermodel() -> dict[str, object]:
    """Build a non-realizability countermodel to scalar ear induction."""
    grouped = orbit_words(5)
    selected_output_orbits = {
        (0x03, 0x03, 0x03, 0x03),
        (0x03, 0x05, 0x03, 0x05),
        (0x03, 0x05, 0x05, 0x03),
        (0x03, 0x05, 0x0A, 0x0C),
        (0x03, 0x05, 0x0C, 0x0A),
    }
    selected_input_orbits = set()
    for representative, words in grouped.items():
        endpoint_xor = representative[0] ^ representative[1]
        if endpoint_xor.bit_count() != 2:
            selected_input_orbits.add(representative)
            continue
        output = e1_output_representative(words[0])
        if output in selected_output_orbits:
            selected_input_orbits.add(representative)

    relation = frozenset(
        word
        for representative in selected_input_orbits
        for word in grouped[representative]
    )
    image = add_ear(relation, 0, 1, 1)
    assert len(selected_input_orbits) == 46
    assert len(relation) == 4_620
    assert len(relation_orbits(image)) == 5
    assert len(image) == 370
    pair_projection_sizes = {
        f"{left},{right}": len({
            (word[left], word[right]) for word in relation
        })
        for left, right in combinations(range(5), 2)
    }
    assert set(pair_projection_sizes.values()) == {100}
    assert elementary_switching_closed(selected_input_orbits)
    assert elementary_switching_closed(set(relation_orbits(image)))
    cap_hits = tuple(
        len(selected_input_orbits & set(cap))
        for cap in five_cycle_cap_orbit_sets()
    )
    assert min(cap_hits) > 0

    return {
        "classification": (
            "ABSTRACT COLOR-INVARIANT XOR RELATION; "
            "GRAPH REALIZABILITY NOT CLAIMED"
        ),
        "input_color_orbits": len(selected_input_orbits),
        "input_ordered_words": len(relation),
        "input_density": len(relation) / len(valid_words(5)),
        "input_log2_support": math.log2(len(relation)),
        "all_two_coordinate_projection_sizes": pair_projection_sizes,
        "elementary_bichromatic_switching_closed": True,
        "five_cycle_cap_intersection_sizes": cap_hits,
        "one_internal_vertex_ear_image_color_orbits": len(
            relation_orbits(image)
        ),
        "one_internal_vertex_ear_image_ordered_words": len(image),
        "image_density": len(image) / len(valid_words(4)),
        "image_log2_support": math.log2(len(image)),
        "selected_image_orbit_representatives": [
            list(word) for word in sorted(selected_output_orbits)
        ],
        "scope": (
            "Refutes induction from scalar support/density/log-support "
            "even after adding full pair projections, C5-cap hits, and "
            "the elementary single-pair switching test. It is not a "
            "five-pole counterexample; stronger simultaneous-switch and "
            "internal path-topology data are not encoded."
        ),
    }


@lru_cache(maxsize=None)
def position_maps(
    terminals: int,
) -> tuple[tuple[int, ...], ...]:
    representatives = orbit_representatives(terminals)
    index = {
        representative: position
        for position, representative in enumerate(representatives)
    }
    return tuple(
        tuple(
            index[color_representative(tuple(
                word[position] for position in permutation
            ))]
            for word in representatives
        )
        for permutation in permutations(range(terminals))
    )


@lru_cache(maxsize=None)
def canonical_relation_mask(terminals: int, mask: int) -> int:
    best = None
    set_bits = tuple(
        position for position in range(len(orbit_representatives(terminals)))
        if mask >> position & 1
    )
    for mapping in position_maps(terminals):
        transformed = 0
        for position in set_bits:
            transformed |= 1 << mapping[position]
        if best is None or transformed < best:
            best = transformed
    assert best is not None
    return best


@lru_cache(maxsize=None)
def ear_orbit_rows(
    terminals: int,
    internal_vertices: int,
    left: int,
    right: int,
) -> tuple[int, tuple[int, ...]]:
    output_terminals = terminals + internal_vertices - 2
    output_index = {
        representative: position
        for position, representative
        in enumerate(orbit_representatives(output_terminals))
    }
    retained = tuple(
        position for position in range(terminals)
        if position not in (left, right)
    )
    rows = []
    for word in orbit_representatives(terminals):
        row = 0
        for boundary in ear_boundaries(
            word[left], word[right], internal_vertices
        ):
            output = tuple(word[position] for position in retained) + boundary
            row |= 1 << output_index[color_representative(output)]
        rows.append(row)
    return output_terminals, tuple(rows)


def apply_orbit_operator(
    terminals: int,
    mask: int,
    internal_vertices: int,
    left: int,
    right: int,
) -> tuple[int, int]:
    output_terminals, rows = ear_orbit_rows(
        terminals, internal_vertices, left, right
    )
    output = 0
    pending = mask
    while pending:
        bit = pending & -pending
        pending ^= bit
        output |= rows[bit.bit_length() - 1]
    return output_terminals, canonical_relation_mask(
        output_terminals, output
    )


def cycle_relation_mask(terminals: int) -> int:
    index = {
        representative: position
        for position, representative
        in enumerate(orbit_representatives(terminals))
    }
    mask = 0
    for word in cycle_relation(terminals):
        mask |= 1 << index[color_representative(word)]
    return canonical_relation_mask(terminals, mask)


def e2_semigroup() -> dict[str, object]:
    start = cycle_relation_mask(5)
    frontier = {start}
    seen = {start}
    while frontier:
        following = set()
        for mask in frontier:
            for left, right in combinations(range(5), 2):
                output_terminals, output = apply_orbit_operator(
                    5, mask, 2, left, right
                )
                assert output_terminals == 5
                following.add(output)
        following -= seen
        seen |= following
        frontier = following
    assert len(seen) == 7
    assert min(mask.bit_count() for mask in seen) == 46

    ordered = sorted(seen)
    state_index = {mask: index for index, mask in enumerate(ordered)}
    transitions = []
    for mask in ordered:
        targets = sorted({
            state_index[apply_orbit_operator(
                5, mask, 2, left, right
            )[1]]
            for left, right in combinations(range(5), 2)
        })
        transitions.append(targets)
    return {
        "states": len(ordered),
        "minimum_orbit_support": min(
            mask.bit_count() for mask in ordered
        ),
        "state_orbit_supports": [
            mask.bit_count() for mask in ordered
        ],
        "state_masks_hex": [f"{mask:016x}" for mask in ordered],
        "transition_target_state_indices": transitions,
        "theorem_scope": (
            "All five-poles obtained from C5 by any finite sequence of "
            "ears with exactly two internal vertices."
        ),
    }


def restricted_ear_semigroup() -> dict[str, object]:
    """Close C5 under m=1,2,3 while boundary size stays 4,5,6."""
    start = (5, cycle_relation_mask(5))
    frontier = {start}
    seen = {start}
    depth_profile = []
    while frontier:
        following = set()
        for terminals, mask in frontier:
            for internal_vertices in (1, 2, 3):
                output_terminals = terminals + internal_vertices - 2
                if output_terminals not in (4, 5, 6):
                    continue
                for left, right in combinations(range(terminals), 2):
                    following.add(apply_orbit_operator(
                        terminals, mask, internal_vertices, left, right
                    ))
        following -= seen
        if following:
            depth_profile.append({
                "new_states": len(following),
                "minimum_support_by_terminal_count": {
                    str(terminals): min(
                        mask.bit_count()
                        for count, mask in following
                        if count == terminals
                    )
                    for terminals in sorted({
                        count for count, _ in following
                    })
                },
            })
        seen |= following
        frontier = following
    assert len(seen) == 72
    five_supports = [
        mask.bit_count() for terminals, mask in seen if terminals == 5
    ]
    assert min(five_supports) == 46
    return {
        "canonical_relations": len(seen),
        "relations_by_terminal_count": dict(sorted(Counter(
            terminals for terminals, _ in seen
        ).items())),
        "five_terminal_minimum_orbit_support": min(five_supports),
        "five_terminal_support_profile": dict(sorted(Counter(
            five_supports
        ).items())),
        "new_state_depth_profile": depth_profile,
        "theorem_scope": (
            "Relations reachable from the C5 pole while every ear has "
            "1, 2, or 3 internal vertices and every intermediate boundary "
            "size lies in {4,5,6}."
        ),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--extended",
        action="store_true",
        help="also run the slower 4/5/6-terminal ear semigroup closure",
    )
    args = parser.parse_args()

    assert len(B) == 10
    assert len(valid_words(4)) == 640
    assert len(valid_words(5)) == 6_240
    assert len(orbit_representatives(4)) == 10
    assert len(orbit_representatives(5)) == 62
    assert len(cycle_relation(4)) == 580
    assert len(cycle_relation(5)) == 4_620
    assert len(relation_orbits(cycle_relation(4))) == 9
    assert len(relation_orbits(cycle_relation(5))) == 46

    report = {
        "schema": "d5-open-ear-operator-audit-v1",
        "classification": (
            "HUMAN-CHECKABLE OPERATOR / EXACT FINITE AUDITS / "
            "NO UNIVERSAL THEOREM"
        ),
        "boundary_universes": {
            "four_terminals": {
                "ordered_words": len(valid_words(4)),
                "color_orbits": len(orbit_representatives(4)),
                "cycle_relation_words": len(cycle_relation(4)),
                "cycle_relation_orbits": len(
                    relation_orbits(cycle_relation(4))
                ),
            },
            "five_terminals": {
                "ordered_words": len(valid_words(5)),
                "color_orbits": len(orbit_representatives(5)),
                "cycle_relation_words": len(cycle_relation(5)),
                "cycle_relation_orbits": len(
                    relation_orbits(cycle_relation(5))
                ),
            },
        },
        "local_ear_kernel": local_kernel_profiles(),
        "scalar_invariant_countermodel": abstract_scalar_countermodel(),
        "two_internal_vertex_ear_semigroup": e2_semigroup(),
        "restricted_ear_semigroup": (
            restricted_ear_semigroup() if args.extended else None
        ),
        "warning": (
            "The countermodel is an abstract relation, not a graph pole. "
            "The positive semigroup checks cover restricted infinite "
            "ear families only. FiveCDC and the universal 46-orbit claim "
            "remain unresolved."
        ),
    }
    print(json.dumps(report, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
