#!/usr/bin/env python3
"""Exact census for the minimum-extendable-projection frontier.

For every connected cubic graph of the requested even order generated by
nauty-geng, this program:

* checks bridgelessness;
* discards the Tait-colourable graphs (where the claim is immediate);
* enumerates the full binary cycle space;
* finds the minimum cardinality of a cycle h which is a coordinate of a
  nowhere-zero F_2^3-flow; and
* checks whether every such minimum h has a clean two-cycle lift.

The clean-lift test is the exact condition from the accompanying note:
there are binary cycles p,q covering E-h and, for each component W of
(V,E-h), |delta(W) intersect p intersect q| is even.
"""

from __future__ import annotations

import argparse
from collections import Counter
import hashlib
import shutil
import subprocess

import search_fano_all_bad_projection_subspaces as core


def semantic_states(cycles: tuple[int, ...]) -> tuple[tuple[int, int], ...]:
    """Quotient pairs (p,q) by their union and intersection."""
    states = {
        (first | second, first & second)
        for position, first in enumerate(cycles)
        for second in cycles[position:]
    }
    return tuple(
        sorted(
            states,
            key=lambda state: (
                state[0].bit_count(),
                -state[1].bit_count(),
            ),
            reverse=True,
        )
    )


def minimum_projection_profile(
    order: int,
    edges: tuple[tuple[int, int], ...],
) -> tuple[int, int, int]:
    """Return (minimum size, liftable count, clean count) at that size."""
    cycles = core.enumerate_cycles(core.cycle_basis(order, edges))
    states = semantic_states(cycles)
    all_edges = (1 << len(edges)) - 1
    by_size: dict[int, list[int]] = {}
    for projection in cycles:
        if projection:
            by_size.setdefault(projection.bit_count(), []).append(projection)

    for size in sorted(by_size):
        liftable = 0
        clean = 0
        for projection in by_size[size]:
            factor = all_edges ^ projection
            cuts = core.factor_cut_masks(order, edges, factor)
            this_liftable = False
            this_clean = False
            for union, product in states:
                if factor & ~union:
                    continue
                this_liftable = True
                if all(
                    not ((product & cut).bit_count() & 1)
                    for cut in cuts
                ):
                    this_clean = True
                    break
            liftable += int(this_liftable)
            clean += int(this_clean)
        if liftable:
            return size, liftable, clean
    raise AssertionError("a bridgeless cubic graph has no Fano extension")


def generated_rows(geng: str, order: int):
    process = subprocess.Popen(
        [geng, "-cq", "-d3", "-D3", str(order)],
        stdout=subprocess.PIPE,
        text=True,
    )
    assert process.stdout is not None
    yield from (row.strip() for row in process.stdout if row.strip())
    if process.wait():
        raise RuntimeError("nauty-geng failed")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--order", type=int, default=18)
    parser.add_argument("--geng", default=shutil.which("geng"))
    args = parser.parse_args()
    if not args.geng:
        raise SystemExit("nauty-geng not found; pass --geng PATH")
    if args.order < 4 or args.order % 2:
        raise SystemExit("--order must be even and at least four")

    generated = bridgeless = hard = 0
    size_histogram: Counter[int] = Counter()
    digest = hashlib.sha256()
    counterexample = None

    for graph6 in generated_rows(args.geng, args.order):
        generated += 1
        order, edges = core.decode_graph6(graph6)
        assert order == args.order
        assert len(edges) * 2 == 3 * order
        if not all(
            core.connected_without_edge(order, edges, edge)
            for edge in range(len(edges))
        ):
            continue
        bridgeless += 1
        if core.is_tait_colorable(order, edges):
            continue
        hard += 1
        size, liftable, clean = minimum_projection_profile(order, edges)
        size_histogram[size] += 1
        record = f"{graph6}\t{size}\t{liftable}\t{clean}\n"
        digest.update(record.encode("ascii"))
        print(record, end="", flush=True)
        if clean != liftable:
            counterexample = record.strip()
            break

    print(f"order={args.order}")
    print(f"generated_connected_cubic={generated}")
    print(f"bridgeless={bridgeless}")
    print(f"non_tait={hard}")
    print(
        "minimum_size_histogram="
        + ",".join(f"{key}:{size_histogram[key]}" for key in size_histogram)
    )
    print(f"record_sha256={digest.hexdigest()}")
    print(f"all_minimum_extendable_clean={counterexample is None}")
    if counterexample is not None:
        print(f"first_counterexample={counterexample}")
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
