#!/usr/bin/env python3
"""Verify the toric kernel and next exact SAGBI generators after W."""

from __future__ import annotations

import sympy as sp

import verify_weighted_lift_degree_six_ternary_boundary_wronskian_closure as boundary
import verify_weighted_lift_sagbi_saturation_next_generator_audit as saturation


u = boundary.u
f = boundary.f_symbol


def monomial(
    generators: list[sp.Poly],
    exponents: tuple[int, ...],
) -> sp.Poly:
    result = sp.Poly(1, u, f)
    for exponent, generator in zip(exponents, generators):
        if exponent:
            result *= generator**exponent
    return result


def leading_coefficient(
    coefficients: list[sp.Rational],
    exponents: tuple[int, ...],
) -> sp.Rational:
    result = sp.Integer(1)
    for exponent, coefficient in zip(exponents, coefficients):
        result *= coefficient**exponent
    return sp.factor(result)


def cancel_pair(
    polynomial: sp.Poly,
    pair: tuple[int, int],
    exponents: tuple[int, ...],
    generators: list[sp.Poly],
) -> tuple[sp.Poly, sp.Rational]:
    reducer = monomial(generators, exponents)
    target = u ** pair[0] * f ** pair[1]
    ratio = sp.factor(
        polynomial.coeff_monomial(target)
        / reducer.coeff_monomial(target)
    )
    assert ratio != 0
    remainder = polynomial - ratio * reducer
    assert remainder.coeff_monomial(target) == 0
    return remainder, ratio


def build_generators() -> tuple[
    list[sp.Poly],
    list[sp.Rational],
]:
    completed_w, template_t, _ = (
        saturation.build_boundary_subduction()
    )
    _, _, _, template_a, template_b, template_u = (
        boundary.boundary_functions()
    )
    expressions = [
        f,
        template_b,
        template_a,
        template_t,
        template_u,
        completed_w,
    ]
    pairs = [
        (0, 1),
        (5, 4),
        (6, 4),
        (25, 19),
        (20, 17),
        (25, 20),
    ]
    generators = [sp.Poly(expression, u, f) for expression in expressions]
    coefficients = [
        generator.coeff_monomial(u**i * f**j)
        for generator, (i, j) in zip(generators, pairs)
    ]
    assert all(coefficient != 0 for coefficient in coefficients)
    return generators, coefficients


def verify_toric_kernel_and_markov_basis() -> None:
    matrix = sp.Matrix(
        [
            [1, -1, -2, -6, -5, -7],
            [0, 5, 6, 25, 20, 25],
            [1, 4, 4, 19, 17, 20],
        ]
    )
    lattice_basis = [
        sp.Matrix([4, -6, 5, 0, 0, 0]),
        sp.Matrix([1, -5, 0, 1, 0, 0]),
        sp.Matrix([1, -1, 0, 0, -1, 1]),
    ]
    assert matrix.rank() == 3
    assert all(matrix * vector == sp.zeros(3, 1) for vector in lattice_basis)

    z, c, b, a, t, q_u, w = sp.symbols("z c b a t q_u w")
    lattice_binomials = [
        c**4 * a**5 - b**6,
        c * t - b**5,
        c * w - b * q_u,
    ]
    saturation_equation = 1 - z * c * b * a * t * q_u * w
    saturated = sp.groebner(
        lattice_binomials + [saturation_equation],
        z,
        c,
        b,
        a,
        t,
        q_u,
        w,
        order="lex",
    )
    eliminated = [
        polynomial.as_expr()
        for polynomial in saturated.polys
        if not polynomial.as_expr().has(z)
    ]

    markov = [
        b**5 - c * t,
        b * q_u - c * w,
        c**3 * a**5 - b * t,
        b**4 * w - t * q_u,
        c**2 * b**4 * a**5 - t**2,
        c**2 * a**5 * q_u - t * w,
        c * a**5 * q_u**3 - b**3 * w**3,
        a**5 * q_u**4 - b**2 * w**4,
    ]
    markov_groebner = sp.groebner(
        markov,
        c,
        b,
        a,
        t,
        q_u,
        w,
        order="lex",
    )
    saturated_groebner = sp.groebner(
        eliminated,
        c,
        b,
        a,
        t,
        q_u,
        w,
        order="lex",
    )
    assert [
        polynomial.monic().as_expr()
        for polynomial in markov_groebner.polys
    ] == [
        polynomial.monic().as_expr()
        for polynomial in saturated_groebner.polys
    ]

    # No displayed Markov binomial belongs to the ideal generated by
    # the other seven.
    variables = (c, b, a, t, q_u, w)
    for index, binomial in enumerate(markov):
        others = markov[:index] + markov[index + 1 :]
        other_groebner = sp.groebner(
            others,
            *variables,
            order="grevlex",
        )
        assert other_groebner.reduce(binomial)[1] != 0


def verify_cw_zero_subduction(
    generators: list[sp.Poly],
    coefficients: list[sp.Rational],
) -> None:
    bu = (0, 1, 0, 0, 1, 0)
    cw = (1, 0, 0, 0, 0, 1)
    polynomial = (
        leading_coefficient(coefficients, cw)
        * monomial(generators, bu)
        - leading_coefficient(coefficients, bu)
        * monomial(generators, cw)
    )
    corrections = [
        ((26, 20), (0, 4, 1, 0, 0, 0)),
        ((25, 19), (0, 0, 0, 1, 0, 0)),
    ]
    ratios = []
    for pair, exponents in corrections:
        polynomial, ratio = cancel_pair(
            polynomial,
            pair,
            exponents,
            generators,
        )
        ratios.append(ratio)
    assert ratios == [
        -sp.Rational(
            34098091069723790625,
            12849356976252738230319332164410926000343082860544,
        ),
        -sp.Rational(
            117766993449375,
            42382290729925007165141632705051492352,
        ),
    ]
    assert polynomial.is_zero


def build_v(
    generators: list[sp.Poly],
    coefficients: list[sp.Rational],
) -> sp.Poly:
    b4w = (0, 4, 0, 0, 0, 1)
    tu = (0, 0, 0, 1, 1, 0)
    polynomial = (
        leading_coefficient(coefficients, tu)
        * monomial(generators, b4w)
        - leading_coefficient(coefficients, b4w)
        * monomial(generators, tu)
    )
    corrections = [
        ((46, 35), (3, 2, 6, 0, 0, 0)),
        ((44, 35), (2, 0, 4, 0, 1, 0)),
        ((45, 34), (2, 3, 5, 0, 0, 0)),
        ((43, 34), (2, 0, 3, 0, 0, 1)),
        ((44, 33), (1, 4, 4, 0, 0, 0)),
        ((42, 33), (1, 1, 2, 0, 0, 1)),
        ((43, 32), (1, 0, 3, 1, 0, 0)),
    ]
    for pair, exponents in corrections:
        polynomial, _ = cancel_pair(
            polynomial,
            pair,
            exponents,
            generators,
        )
    return polynomial


def pareto_frontier(polynomial: sp.Poly) -> list[tuple[int, int]]:
    pairs = [
        pair
        for pair, coefficient in polynomial.terms()
        if coefficient != 0
    ]
    return [
        (i, j)
        for i, j in pairs
        if not any(
            i2 >= i
            and j2 >= j
            and (i2 > i or j2 > j)
            for i2, j2 in pairs
        )
    ]


def verify_v(
    generators: list[sp.Poly],
    coefficients: list[sp.Rational],
) -> tuple[sp.Poly, sp.Rational]:
    polynomial_v = build_v(generators, coefficients)
    coefficient_v = polynomial_v.coeff_monomial(u**40 * f**33)
    assert coefficient_v == sp.Rational(
        646429908327484130859375,
        7185034270063548786562948887160069885258119973112902428748815183129257967616,
    )
    assert pareto_frontier(polynomial_v) == [
        (42, 31),
        (41, 32),
        (40, 33),
    ]
    for graph_degree in range(2, 30):
        terms = polynomial_v.terms()
        maximum = max(
            i + graph_degree * j
            for (i, j), coefficient in terms
            if coefficient != 0
        )
        assert [
            pair
            for pair, coefficient in terms
            if coefficient != 0
            and pair[0] + graph_degree * pair[1] == maximum
        ] == [(40, 33)]

    verify_v_projected_classification(
        polynomial_v,
        coefficient_v,
        generators,
    )
    return polynomial_v, coefficient_v


def verify_v_projected_classification(
    polynomial_v: sp.Poly,
    coefficient_v: sp.Rational,
    generators: list[sp.Poly],
) -> None:
    graph_degree = sp.symbols("L", integer=True, positive=True)
    b, a, t, q_u, w = sp.symbols(
        "b a t q_u w",
        integer=True,
        nonnegative=True,
    )
    c = -11 + b + 2 * a + 6 * t + 5 * q_u + 7 * w
    projected_degree = (
        graph_degree * c
        + (5 + 4 * graph_degree) * b
        + (6 + 4 * graph_degree) * a
        + (25 + 19 * graph_degree) * t
        + (20 + 17 * graph_degree) * q_u
        + (25 + 20 * graph_degree) * w
    )
    diophantine = sp.expand(
        projected_degree - (40 + 33 * graph_degree)
    )
    expected = sp.expand(
        (graph_degree + 1)
        * (5 * b + 6 * a + 25 * t + 22 * q_u + 27 * w - 44)
        - 2 * (q_u + w)
        + 4
    )
    assert sp.expand(diophantine - expected) == 0

    # Degree positivity gives q_u,w <= 1 uniformly for L>=2.
    assert sp.expand(
        2 * (20 + 17 * graph_degree)
        - (40 + 33 * graph_degree)
    ) == graph_degree
    assert sp.expand(
        2 * (25 + 20 * graph_degree)
        - (40 + 33 * graph_degree)
    ) == 10 + 7 * graph_degree

    # For L=2 or L>=4, divisibility forces q_u=w=1.  The
    # remaining nonnegative equation would be -5.
    possible_right_sides = {
        (q_value, w_value): 2 * (q_value + w_value) - 4
        for q_value in (0, 1)
        for w_value in (0, 1)
    }
    assert set(possible_right_sides.values()) == {-4, -2, 0}
    assert [
        pair
        for pair, value in possible_right_sides.items()
        if value % 3 == 0
    ] == [(1, 1)]
    assert [
        pair
        for pair, value in possible_right_sides.items()
        if value == 0
    ] == [(1, 1)]
    assert 44 - 22 - 27 == -5

    # At L=3, q_u=w=0 is also possible and the residual equation is
    # 5b+6a+25t=43.  Its two solutions give CA^3T and B^5A^3.
    assert [
        pair
        for pair, value in possible_right_sides.items()
        if value % 4 == 0
    ] == [(0, 0), (1, 1)]
    ca3t = (1, 0, 3, 1, 0, 0)
    b5a3 = (0, 5, 3, 0, 0, 0)
    projected_vectors_l3 = [
        (1, 3),
        (-1, 17),
        (-2, 18),
        (-6, 82),
        (-5, 71),
        (-7, 85),
    ]
    target_l3 = (-11, 139)
    for factorization in (ca3t, b5a3):
        assert tuple(
            sum(
                factorization[index]
                * projected_vectors_l3[index][coordinate]
                for index in range(6)
            )
            for coordinate in range(2)
        ) == target_l3
    assert 5 * 5 + 6 * 3 == 43
    assert 6 * 3 + 25 == 43

    # A concise exact audit of the first cubic reduction.  If
    # f=r*u^3+d*u^2+..., only drops zero and one are needed.
    r = sp.symbols("r", nonzero=True)
    d = sp.symbols("d")

    def cubic_coefficient(
        polynomial: sp.Poly,
        target_degree: int,
    ) -> sp.Expr:
        result = sp.Integer(0)
        for (u_degree, f_degree), coefficient in polynomial.terms():
            drop = u_degree + 3 * f_degree - target_degree
            if drop == 0:
                result += coefficient * r**f_degree
            elif drop == 1:
                result += (
                    coefficient
                    * f_degree
                    * r ** (f_degree - 1)
                    * d
                )
        return sp.factor(result)

    ca3t_polynomial = monomial(
        generators,
        (1, 0, 3, 1, 0, 0),
    )
    ratio = sp.factor(
        cubic_coefficient(polynomial_v, 139)
        / cubic_coefficient(ca3t_polynomial, 139)
    )
    next_coefficient = sp.factor(
        cubic_coefficient(polynomial_v, 138)
        - ratio * cubic_coefficient(ca3t_polynomial, 138)
    )
    assert sp.factor(
        next_coefficient - coefficient_v * d * r**32
    ) == 0


def verify_cv_zero_subduction(
    generators: list[sp.Poly],
    coefficients: list[sp.Rational],
) -> None:
    cv = (1, 0, 0, 0, 0, 0, 1)
    u2 = (0, 0, 0, 0, 2, 0, 0)
    polynomial = (
        leading_coefficient(coefficients, u2)
        * monomial(generators, cv)
        - leading_coefficient(coefficients, cv)
        * monomial(generators, u2)
    )
    corrections = [
        ((41, 33), (1, 2, 1, 0, 0, 1, 0)),
        ((42, 32), (4, 0, 7, 0, 0, 0, 0)),
        ((40, 32), (0, 3, 0, 0, 0, 1, 0)),
        ((41, 31), (3, 1, 6, 0, 0, 0, 0)),
        ((40, 30), (2, 2, 5, 0, 0, 0, 0)),
        ((38, 30), (1, 0, 3, 0, 1, 0, 0)),
        ((39, 29), (1, 3, 4, 0, 0, 0, 0)),
        ((37, 29), (1, 0, 2, 0, 0, 1, 0)),
        ((38, 28), (0, 4, 3, 0, 0, 0, 0)),
        ((36, 28), (0, 1, 1, 0, 0, 1, 0)),
        ((37, 27), (0, 0, 2, 1, 0, 0, 0)),
    ]
    for pair, exponents in corrections:
        polynomial, _ = cancel_pair(
            polynomial,
            pair,
            exponents,
            generators,
        )
    assert polynomial.is_zero


def build_and_verify_x(
    generators: list[sp.Poly],
    coefficients: list[sp.Rational],
) -> None:
    uw = (0, 0, 0, 0, 1, 1, 0)
    bv = (0, 1, 0, 0, 0, 0, 1)
    polynomial = (
        leading_coefficient(coefficients, bv)
        * monomial(generators, uw)
        - leading_coefficient(coefficients, uw)
        * monomial(generators, bv)
    )
    corrections = [
        ((46, 36), (0, 3, 1, 0, 0, 1, 0)),
        ((47, 35), (3, 1, 7, 0, 0, 0, 0)),
    ]
    for pair, exponents in corrections:
        polynomial, _ = cancel_pair(
            polynomial,
            pair,
            exponents,
            generators,
        )
    coefficient_x = polynomial.coeff_monomial(u**45 * f**35)
    assert coefficient_x == sp.Rational(
        19677099045075849323526515486997127532958984375,
        4753783574128806258117724534569839285153295438529048764295676190272725307777236595256331251079400117251896323723308382663349555429376,
    )
    assert pareto_frontier(polynomial) == [(46, 34), (45, 35)]
    for graph_degree in range(2, 30):
        maximum = max(
            i + graph_degree * j
            for (i, j), coefficient in polynomial.terms()
            if coefficient != 0
        )
        assert [
            pair
            for pair, coefficient in polynomial.terms()
            if coefficient != 0
            and pair[0] + graph_degree * pair[1] == maximum
        ] == [(45, 35)]

    verify_x_projected_nonmembership()


def verify_x_projected_nonmembership() -> None:
    graph_degree = sp.symbols("L", integer=True, positive=True)
    b, a, t, q_u, w, v = sp.symbols(
        "b a t q_u w v",
        integer=True,
        nonnegative=True,
    )
    c = (
        -12
        + b
        + 2 * a
        + 6 * t
        + 5 * q_u
        + 7 * w
        + 11 * v
    )
    projected_degree = (
        graph_degree * c
        + (5 + 4 * graph_degree) * b
        + (6 + 4 * graph_degree) * a
        + (25 + 19 * graph_degree) * t
        + (20 + 17 * graph_degree) * q_u
        + (25 + 20 * graph_degree) * w
        + (40 + 33 * graph_degree) * v
    )
    diophantine = sp.expand(
        projected_degree - (45 + 35 * graph_degree)
    )
    expected = sp.expand(
        (graph_degree + 1)
        * (
            5 * b
            + 6 * a
            + 25 * t
            + 22 * q_u
            + 27 * w
            + 44 * v
            - 47
        )
        - 2 * q_u
        - 2 * w
        - 4 * v
        + 2
    )
    assert sp.expand(diophantine - expected) == 0

    # These strict inequalities prove q_u<=2, w<=1, v<=1, t<=1.
    target_degree = 45 + 35 * graph_degree
    assert sp.expand(
        3 * (20 + 17 * graph_degree) - target_degree
    ) == 15 + 16 * graph_degree
    assert sp.expand(
        2 * (25 + 20 * graph_degree) - target_degree
    ) == 5 + 5 * graph_degree
    assert sp.expand(
        2 * (40 + 33 * graph_degree) - target_degree
    ) == 35 + 31 * graph_degree
    assert sp.expand(
        2 * (25 + 19 * graph_degree) - target_degree
    ) == 5 + 3 * graph_degree

    triples = [
        (q_value, w_value, v_value)
        for q_value in range(3)
        for w_value in range(2)
        for v_value in range(2)
    ]

    def residual(triple: tuple[int, int, int]) -> int:
        q_value, w_value, v_value = triple
        return 2 * q_value + 2 * w_value + 4 * v_value - 2

    assert min(map(residual, triples)) == -2
    assert max(map(residual, triples)) == 8
    zero_triples = [
        triple for triple in triples if residual(triple) == 0
    ]
    assert zero_triples == [(0, 1, 0), (1, 0, 0)]

    # For 2<=L<=7, classify the divisibility cases exactly.  Every
    # nonzero residual case gives a negative right side for
    # 5b+6a+25t.
    expected_negative = {
        2: [-44, -39],
        3: [-23, -18, -23, -66],
        4: [],
        5: [-45, -40],
        6: [],
        7: [-67],
    }
    for degree in range(2, 8):
        negative_values = []
        for q_value, w_value, v_value in triples:
            value = residual((q_value, w_value, v_value))
            if value % (degree + 1) != 0 or value == 0:
                continue
            right_side = (
                47
                + value // (degree + 1)
                - 22 * q_value
                - 27 * w_value
                - 44 * v_value
            )
            negative_values.append(right_side)
        assert negative_values == expected_negative[degree]
        assert all(value < 0 for value in negative_values)

    # The two residual-zero equations have only the displayed
    # nonnegative solutions; each violates c>=0.
    assert 5 * 4 == 20
    assert -12 + 4 + 7 == -1
    assert 5 * 5 == 25
    assert -12 + 5 + 5 == -2
    assert 25 == 25
    assert -12 + 6 + 5 == -1


def verify_linear_graph_branch(
    generators: list[sp.Poly],
) -> None:
    fixed_graph = sp.Rational(91, 34) - sp.Rational(57, 34) * u
    specialized = [
        sp.Poly(generator.as_expr().subs(f, fixed_graph), u)
        for generator in generators
    ]
    assert [polynomial.degree() for polynomial in specialized] == [
        1,
        9,
        10,
        44,
        37,
        45,
    ]
    leading = [polynomial.LC() for polynomial in specialized]

    def specialized_monomial(exponents: tuple[int, ...]) -> sp.Poly:
        result = sp.Poly(1, u)
        for exponent, generator in zip(exponents, specialized):
            if exponent:
                result *= generator**exponent
        return result

    bu = (0, 1, 0, 0, 1, 0)
    cw = (1, 0, 0, 0, 0, 1)
    coefficient_bu = sp.prod(
        coefficient**exponent
        for coefficient, exponent in zip(leading, bu)
    )
    coefficient_cw = sp.prod(
        coefficient**exponent
        for coefficient, exponent in zip(leading, cw)
    )
    remainder = (
        coefficient_cw * specialized_monomial(bu)
        - coefficient_bu * specialized_monomial(cw)
    )
    assert remainder.degree() == 45
    assert remainder.LC() != 0

    # Eliminating c from a hypothetical factorization of (-6,45)
    # gives an even left side equal to 51.
    assert all(
        coefficient % 2 == 0
        for coefficient in (10, 12, 50, 42, 52)
    )
    assert 51 % 2 == 1


def main() -> None:
    verify_toric_kernel_and_markov_basis()
    generators, coefficients = build_generators()
    verify_cw_zero_subduction(generators, coefficients)
    polynomial_v, coefficient_v = verify_v(generators, coefficients)
    generators_v = generators + [polynomial_v]
    coefficients_v = coefficients + [coefficient_v]
    verify_cv_zero_subduction(generators_v, coefficients_v)
    build_and_verify_x(generators_v, coefficients_v)
    verify_linear_graph_branch(generators)
    print("verified: full rank-three toric kernel after adjoining W")
    print("verified: exact minimal eight-binomial Markov basis")
    print("verified: CW~BU subducts exactly to zero")
    print("verified: formal B^4W~TU frontier is (-11,40,33)")
    print("verified: V is projected-new exactly for L=2 and L>=4")
    print("verified: L=3 has exactly CA^3T and B^5A^3 reducers")
    print("verified: CV~U^2 subducts exactly to zero")
    print("verified: X is projected-new for every L>=2")
    print("verified: L=1 immediately branches at CW~BU")
    print("RESULT: displayed SAGBI set is incomplete in the stated ranges")


if __name__ == "__main__":
    main()
