#!/usr/bin/env python3
"""Exclude every quartic square-top tail with arbitrary affine lower terms.

For

    M = r*a^2 + s*a*H + q*H^2,
    K = M^2 + k0 + k1*a + k2*H,

this verifies that both a+a^2*(H^2-12a)*K and
H+a^2*(H^2-12a)*K have a finite critical point whenever M is nonzero.
The large exact resultant/coefficient-ideal calculations are delegated to
Singular; the small derivative and leading-coefficient identities are
checked independently with SymPy.
"""

import shutil
import subprocess

import sympy as sp


A, H = sp.symbols("A H")
r, s, q, k0, k1, k2 = sp.symbols("r s q k0 k1 k2")
delta = H**2 - 12 * A
M = r * A**2 + s * A * H + q * H**2
K = M**2 + k0 + k1 * A + k2 * H


def h_leading_coefficient(polynomial):
    return sp.factor(sp.Poly(polynomial, H).LC())


# These coefficients ensure that every nonzero-A resultant root used below
# represents a finite common H-root rather than a degree-drop artifact.
for base in (A, H):
    F = sp.expand(base + A**2 * delta * K)
    assert h_leading_coefficient(sp.diff(F, A)) == 2 * A * q**2
    assert h_leading_coefficient(sp.diff(F, H)) == 6 * A**2 * q**2

K_q0 = sp.expand(K.subs(q, 0))
for base in (A, H):
    F = sp.expand(base + A**2 * delta * K_q0)
    assert h_leading_coefficient(sp.diff(F, A)) == 4 * A**3 * s**2
    assert h_leading_coefficient(sp.diff(F, H)) == 4 * A**4 * s**2

K_qs0 = r**2 * A**4 + k0 + k1 * A + k2 * H
for base in (A, H):
    F = sp.expand(base + A**2 * delta * K_qs0)
    assert h_leading_coefficient(sp.diff(F, A)) == 2 * A * k2
    assert h_leading_coefficient(sp.diff(F, H)) == 3 * A**2 * k2


SINGULAR = shutil.which("Singular") or "/opt/homebrew/bin/Singular"
if not shutil.which("Singular") and not shutil.which(SINGULAR):
    raise RuntimeError("Singular is required for this exact verifier")

PROGRAM = r"""
option(redSB);

// Chart q!=0.  Both residuals have nonzero constant coefficient.
ring Rq=(0,r,s,q,k0,k1,k2),(A,H),dp;
poly D=H^2-12*A;
poly M=r*A^2+s*A*H+q*H^2;
poly K=M^2+k0+k1*A+k2*H;

poly Fa=A+A^2*D*K;
poly Za=resultant(diff(Fa,A),diff(Fa,H),H);
poly Pa=Za/((-8*q^5)*A^12);
if (Za-(-8*q^5)*A^12*Pa!=0) { "FAIL_q_a_division"; }
if (deg(Pa)!=28) { "FAIL_q_a_degree"; }
matrix Cqa=coeffs(Pa,A);
if (Cqa[1,1]!=-5832*q^7) { "FAIL_q_a_constant"; }

poly Fb=H+A^2*D*K;
poly Zb=resultant(diff(Fb,A),diff(Fb,H),H);
poly Pb=Zb/((-8*q^5)*A^5);
if (Zb-(-8*q^5)*A^5*Pb!=0) { "FAIL_q_b_division"; }
if (deg(Pb)!=35) { "FAIL_q_b_degree"; }
matrix Cqb=coeffs(Pb,A);
if (Cqb[1,1]!=-4*q^5) { "FAIL_q_b_constant"; }

ring Sq=0,(z,r,s,q,k0,k1,k2,A),dp;
poly Pqa=imap(Rq,Pa);
matrix C1=coeffs(Pqa,A);
ideal I1=0;
int i;
for (i=2; i<=nrows(C1); i++) { I1=I1,C1[i,1]; }
ideal J1=I1,z*q-1;
ideal G1=std(J1);
if (reduce(1,G1)!=0) { "FAIL_q_a_positive_coefficients"; }

poly Pqb=imap(Rq,Pb);
matrix C2=coeffs(Pqb,A);
ideal I2=0;
for (i=2; i<=nrows(C2); i++) { I2=I2,C2[i,1]; }
ideal J2=I2,z*q-1;
ideal G2=std(J2);
if (reduce(1,G2)!=0) { "FAIL_q_b_positive_coefficients"; }
"PASS_q_chart";

// Chart q=0, s!=0.  A polynomial over an algebraically closed field has
// no nonzero root precisely when it is a monomial.  For every possible
// retained coefficient, the ideal generated by all other coefficients,
// saturated by s, is the unit ideal.  Hence neither residual can specialize
// to a monomial.
ring Rs=(0,r,s,k0,k1,k2),(A,H),dp;
poly D=H^2-12*A;
poly M=r*A^2+s*A*H;
poly K=M^2+k0+k1*A+k2*H;

poly Fa=A+A^2*D*K;
poly Za=resultant(diff(Fa,A),diff(Fa,H),H);
poly Pa=Za/(4*s^2*A^11);
if (Za-4*s^2*A^11*Pa!=0) { "FAIL_s_a_division"; }
if (deg(Pa)!=22) { "FAIL_s_a_degree"; }
matrix Csa=coeffs(Pa,A);
if (Csa[1,1]!=27*k2^4) { "FAIL_s_a_constant"; }

poly Fb=H+A^2*D*K;
poly Zb=resultant(diff(Fb,A),diff(Fb,H),H);
poly Pb=Zb/(4*s^2*A^7);
if (Zb-4*s^2*A^7*Pb!=0) { "FAIL_s_b_division"; }
if (deg(Pb)!=26) { "FAIL_s_b_degree"; }
matrix Csb=coeffs(Pb,A);
if (Csb[1,1]!=4*k2^3) { "FAIL_s_b_constant"; }

ring Ss=0,(z,r,s,k0,k1,k2,A),dp;
proc monomialFailures(poly P, poly unit)
{
  matrix C=coeffs(P,A);
  ideal I=0;
  ideal J=0;
  ideal G=0;
  int failures=0;
  int omit;
  int j;
  for (omit=1; omit<=nrows(C); omit++)
  {
    I=0;
    for (j=1; j<=nrows(C); j++)
    {
      if (j!=omit) { I=I,C[j,1]; }
    }
    J=I,z*unit-1;
    G=std(J);
    if (reduce(1,G)!=0) { failures=failures+1; }
  }
  return(failures);
}
poly Psa=imap(Rs,Pa);
poly Psb=imap(Rs,Pb);
if (monomialFailures(Psa,s)!=0) { "FAIL_s_a_monomial_chart"; }
if (monomialFailures(Psb,s)!=0) { "FAIL_s_b_monomial_chart"; }
"PASS_s_chart";

// Last mixed chart q=s=0, r*k2!=0.  If k2=0, K is univariate in A and
// is already covered by the all-degree univariate-tail theorem.
ring Rr=(0,r,k0,k1,k2),(A,H),dp;
poly D=H^2-12*A;
poly K=r^2*A^4+k0+k1*A+k2*H;

poly Fa=A+A^2*D*K;
poly Za=resultant(diff(Fa,A),diff(Fa,H),H);
poly Pa=Za/((-k2)*A^6);
if (Za-(-k2)*A^6*Pa!=0) { "FAIL_r_a_division"; }
if (deg(Pa)!=19) { "FAIL_r_a_degree"; }
matrix Cra=coeffs(Pa,A);
if (Cra[1,1]!=-27*k2^2) { "FAIL_r_a_constant"; }

poly Fb=H+A^2*D*K;
poly Zb=resultant(diff(Fb,A),diff(Fb,H),H);
poly Pb=Zb/((-k2)*A^2);
if (Zb-(-k2)*A^2*Pb!=0) { "FAIL_r_b_division"; }
if (deg(Pb)!=23) { "FAIL_r_b_degree"; }
matrix Crb=coeffs(Pb,A);
if (Crb[1,1]!=-4*k2) { "FAIL_r_b_constant"; }

ring Sr=0,(z,r,k0,k1,k2,A),dp;
poly Pra=imap(Rr,Pa);
matrix C1=coeffs(Pra,A);
ideal I1=0;
int i;
for (i=2; i<=nrows(C1); i++) { I1=I1,C1[i,1]; }
ideal J1=I1,z*r*k2-1;
ideal G1=std(J1);
if (reduce(1,G1)!=0) { "FAIL_r_a_positive_coefficients"; }

poly Prb=imap(Rr,Pb);
matrix C2=coeffs(Prb,A);
ideal I2=0;
for (i=2; i<=nrows(C2); i++) { I2=I2,C2[i,1]; }
ideal J2=I2,z*r*k2-1;
ideal G2=std(J2);
if (reduce(1,G2)!=0) { "FAIL_r_b_positive_coefficients"; }
"PASS_r_chart";
quit;
"""

completed = subprocess.run(
    [SINGULAR, "-q"],
    input=PROGRAM,
    text=True,
    capture_output=True,
    check=True,
)
output = completed.stdout + completed.stderr
assert "FAIL_" not in output, output
for sentinel in ("PASS_q_chart", "PASS_s_chart", "PASS_r_chart"):
    assert sentinel in output, output

print("verified q!=0 quartic-square affine-lower resultant charts")
print("verified q=0, s!=0 residuals cannot specialize to monomials")
print("verified q=s=0, r*k2!=0 resultant charts")
print("q=s=k2=0 is the existing all-degree univariate K(a) case")
print("RESULT: EVERY QUARTIC SQUARE-TOP K WITH AFFINE LOWER TERMS IS CRITICAL")
