#!/usr/bin/env python3
"""Verify the conductor normal-jet operator and its second Bockstein layer."""

import sympy as sp


z = sp.symbols("z")
p, q = sp.symbols("p q", integer=True, positive=True)
f, fp, g, gp = sp.symbols("f fp g gp")
A, B = sp.symbols("A B")
At, Az, Bt, Bz = sp.symbols("At Az Bt Bz")
delta_t, delta_z = sp.symbols("delta_t delta_z")

ca = z * gp - q * g
cb = p * f - z * fp

# Substitute the conductor jets of F=f+delta*A and G=g+delta*B into
# the exact recurrence.  The delta^0 term is the normal-jet operator.
Ft0 = delta_t * A
Fz0 = fp + delta_z * A
Gt0 = delta_t * B
Gz0 = gp + delta_z * B
L0 = sp.expand(p * f * Gt0 - q * Ft0 * g + z * (Ft0 * Gz0 - Fz0 * Gt0))
assert sp.expand(L0 - delta_t * (ca * A + cb * B)) == 0

# The coefficient of delta before adding second normal jets.
L1 = sp.expand(
    p * (f * Bt + A * delta_t * B)
    - q * (delta_t * A * B + At * g)
    + z
    * (
        delta_t * A * Bz
        + At * (gp + delta_z * B)
        - (fp + delta_z * A) * Bt
        - Az * delta_t * B
    )
)

# Verify L0+delta*L1 by a direct first-order expansion.
epsilon = sp.symbols("epsilon")
F = f + epsilon * A
G = g + epsilon * B
Ft = delta_t * A + epsilon * At
Fz = fp + delta_z * A + epsilon * Az
Gt = delta_t * B + epsilon * Bt
Gz = gp + delta_z * B + epsilon * Bz
L = sp.expand(p * F * Gt - q * Ft * G + z * (Ft * Gz - Fz * Gt))
assert sp.expand(L.coeff(epsilon, 0) - L0) == 0
assert sp.expand(L.coeff(epsilon, 1) - L1) == 0

# Adding second normal jets F=f+delta*A+delta^2*C and
# G=g+delta*B+delta^2*E contributes twice the same normal operator.
C, E = sp.symbols("C E")
Ct, Cz, Et, Ez = sp.symbols("Ct Cz Et Ez")
F_second = f + epsilon * A + epsilon**2 * C
G_second = g + epsilon * B + epsilon**2 * E
Ft_second = (
    delta_t * A
    + epsilon * (At + 2 * delta_t * C)
    + epsilon**2 * Ct
)
Fz_second = (
    fp
    + delta_z * A
    + epsilon * (Az + 2 * delta_z * C)
    + epsilon**2 * Cz
)
Gt_second = (
    delta_t * B
    + epsilon * (Bt + 2 * delta_t * E)
    + epsilon**2 * Et
)
Gz_second = (
    gp
    + delta_z * B
    + epsilon * (Bz + 2 * delta_z * E)
    + epsilon**2 * Ez
)
L_second = sp.expand(
    p * F_second * Gt_second
    - q * Ft_second * G_second
    + z
    * (
        Ft_second * Gz_second
        - Fz_second * Gt_second
    )
)
second_jet_operator = 2 * delta_t * (ca * C + cb * E)
assert sp.expand(
    L_second.coeff(epsilon, 1)
    - L1
    - second_jet_operator
) == 0

# For delta=9t^2-12tz-9z+4z^2, its normal derivative squares to 324z
# on the conductor.
t = sp.symbols("t")
delta = 9 * t**2 - 12 * t * z - 9 * z + 4 * z**2
eta = sp.diff(delta, t)
assert sp.expand(eta**2 - 36 * delta - 324 * z) == 0

# If A=A0+A1*eta and B=B0+B1*eta on the conductor, the first equation
# splits into one even and one odd Bezout equation.
A0, A1, B0, B1 = sp.symbols("A0 A1 B0 B1")
eta_formal = sp.symbols("eta_formal")
split_L0 = sp.expand(
    eta_formal
    * (
        ca * (A0 + A1 * eta_formal)
        + cb * (B0 + B1 * eta_formal)
    )
)
split_reduced = sp.rem(
    sp.Poly(split_L0, eta_formal),
    sp.Poly(eta_formal**2 - 324 * z, eta_formal),
).as_expr()
expected_split = (
    eta_formal * (ca * A0 + cb * B0)
    + 324 * z * (ca * A1 + cb * B1)
)
assert sp.expand(split_reduced - expected_split) == 0

# In the useful scaled form f=z^p*f0, g=z^q*g0, the cokernel ideal is
# generated by z^(q+1)g0' and -z^(p+1)f0'.
f0, f0p, g0, g0p = sp.symbols("f0 f0p g0 g0p")
ca_scaled = sp.expand(ca.subs({g: z**q * g0, gp: q * z ** (q - 1) * g0 + z**q * g0p}))
cb_scaled = sp.expand(cb.subs({f: z**p * f0, fp: p * z ** (p - 1) * f0 + z**p * f0p}))
assert sp.simplify(ca_scaled - z ** (q + 1) * g0p) == 0
assert sp.simplify(cb_scaled + z ** (p + 1) * f0p) == 0

# Check the saturated square/cube boundary scalar.
f_square = sp.Rational(4, 9) * z**3
g_cube = z**3 * (4 * z - 1) / 27
ca_square_cube = sp.factor(z * sp.diff(g_cube, z) - 3 * g_cube)
cb_square_cube = sp.factor(2 * f_square - z * sp.diff(f_square, z))
assert ca_square_cube == sp.Rational(4, 27) * z**4
assert cb_square_cube == -sp.Rational(4, 9) * z**3
assert sp.gcd(ca_square_cube, cb_square_cube) == z**3

# The odd equation for a bracket-one pair would force B1(0)=1/144 if
# A1 is regular.  The actual P3 lift has B1(0)=0.
required_B1_at_zero = sp.solve(
    sp.Eq(-sp.Rational(4, 9) * B1, -sp.Rational(1, 324)),
    B1,
)[0]
assert required_B1_at_zero == sp.Rational(1, 144)

# Recover the actual normal jets of the explicit P2,P3 pair.  Its odd
# cube jet vanishes at z=0, so it misses the saturated scalar.
F_square_exact = (-3 * t**2 + 2 * t * z + 3 * z) ** 2 / 9
G_cube_exact = -(
    (-3 * t**2 + 2 * t * z + 4 * z)
    * (
        9 * t**4
        - 12 * t**3 * z
        + 4 * t**2 * z**2
        - 6 * t**2 * z
        - 2 * t * z**2
        - 2 * z**2
    )
) / 27
A_square_exact = sp.cancel((F_square_exact - f_square) / delta)
B_cube_exact = sp.cancel((G_cube_exact - g_cube) / delta)


def reduce_mod_delta(expression):
    numerator, denominator = sp.fraction(sp.cancel(expression))
    remainder = sp.rem(
        sp.Poly(numerator, t),
        sp.Poly(delta, t),
    ).as_expr()
    return sp.factor(remainder / denominator)


def eta_components(expression):
    reduced = sp.Poly(reduce_mod_delta(expression), t)
    t_coefficient = reduced.coeff_monomial(t)
    constant_coefficient = reduced.coeff_monomial(1)
    odd = sp.factor(t_coefficient / 18)
    even = sp.factor(constant_coefficient + 12 * z * odd)
    return even, odd


A_square_0, A_square_1 = eta_components(A_square_exact)
B_cube_0, B_cube_1 = eta_components(B_cube_exact)
assert A_square_0 == sp.Rational(4, 81) * z**2
assert A_square_1 == sp.Rational(2, 243) * z
assert B_cube_0 == z**2 * (8 * z - 3) / 81
assert B_cube_1 == z**2 * (4 * z + 9) / 2187
assert B_cube_1.subs(z, 0) == 0

# For an arbitrary descended F=f+delta(A0+A1*eta)+O(delta^2), its cusp
# initial at z=0 records the normal jets in its t^2 and t^3 coefficients.
assert sp.expand(
    (
        f
        + delta * (A0 + A1 * eta)
    ).subs(z, 0)
    - (f + 9 * A0 * t**2 + 162 * A1 * t**3)
) == 0

# Evaluate the second Bockstein for every first solution in the
# saturated square/cube boundary model:
#
#   A=a0+a1*eta,  B=(z/3)A+eta/144.
#
# The displayed residual can be killed, for example by
# a0=-4z^2/135 and a1=0.
a0, a1, a0p, a1p = sp.symbols("a0 a1 a0p a1p")
eta_b = sp.symbols("eta_b")
delta_z_on_conductor = -sp.Rational(2, 3) * eta_b - 9
A_b = a0 + a1 * eta_b
At_b = 18 * a1
Az_b = a0p + a1p * eta_b - 12 * a1
B_b = z * A_b / 3 + eta_b / 144
Bt_b = 6 * z * a1 + sp.Rational(1, 8)
Bz_b = A_b / 3 + z * Az_b / 3 - sp.Rational(1, 12)
L1_b = sp.expand(
    2 * (f_square * Bt_b + A_b * eta_b * B_b)
    - 3 * (eta_b * A_b * B_b + At_b * g_cube)
    + z
    * (
        eta_b * A_b * Bz_b
        + At_b
        * (
            sp.diff(g_cube, z)
            + delta_z_on_conductor * B_b
        )
        - (
            sp.diff(f_square, z)
            + delta_z_on_conductor * A_b
        )
        * Bt_b
        - Az_b * eta_b * B_b
    )
)
K_b = -z**3 / 9
second_residual = sp.rem(
    sp.Poly(sp.expand(K_b + L1_b), eta_b),
    sp.Poly(eta_b**2 - 324 * z, eta_b),
).as_expr()
second_polynomial = sp.Poly(second_residual, eta_b)
second_even = sp.factor(second_polynomial.coeff_monomial(1))
second_odd = sp.factor(second_polynomial.coeff_monomial(eta_b))
assert second_even == -z * (27 * a0 + 54 * a0p * z + 4 * z**2) / 24
assert second_odd == -sp.Rational(9, 4) * z * (a1 + a1p * z)
assert sp.expand(
    second_even.subs(
        {
            a0: -sp.Rational(4, 135) * z**2,
            a0p: -sp.Rational(8, 135) * z,
        }
    )
) == 0
assert second_odd.subs({a1: 0, a1p: 0}) == 0

print("verified the exact conductor normal-jet cokernel")
print("verified the delta^2 Bockstein operator")
print("RESULT: THE LINKED SQUARE/CUBE SURVIVOR SATURATES THE FIRST COKERNEL")
