#!/usr/bin/env python3
"""Verify the exact linked-cusp deformation and its square/cube semigroup."""

import sympy as sp


t, c, z = sp.symbols("t c z")
X, Y = sp.symbols("X Y")

a = t + t**2 - c * t**3
b = 2 + 4 * t - 3 * c * t**2

# At c=infinity the Rees chart is generated by X=za, Y=z(b-2), z.
X_normalized = -t**3 + z * (t + t**2)
Y_normalized = -3 * t**2 + 4 * z * t
R = (
    Y**3
    + 27 * X**2
    + z * (-18 * X * Y + 6 * Y**2)
    + z**2 * (-36 * X - Y**2 + 9 * Y)
    + z**3 * (16 * X - 4 * Y)
)
assert sp.expand(R.subs({X: X_normalized, Y: Y_normalized})) == 0
assert sp.expand(R.subs(z, 0) - (Y**3 + 27 * X**2)) == 0

# The normalization is generated over the Rees chart by t.  The exact
# conductor generators are delta and n=t*delta.
delta = 4 * z**2 - 3 * Y - 9 * z
n = Y * z - 9 * X
delta_normalized = sp.factor(
    delta.subs({X: X_normalized, Y: Y_normalized})
)
n_normalized = sp.factor(n.subs({X: X_normalized, Y: Y_normalized}))
assert delta_normalized == 9 * t**2 - 12 * t * z - 9 * z + 4 * z**2
assert sp.expand(n_normalized - t * delta_normalized) == 0

# Modulo (delta,n), X and Y are functions of z alone and R vanishes.
Y_conductor = (4 * z**2 - 9 * z) / 3
X_conductor = Y_conductor * z / 9
assert sp.expand(
    R.subs({X: X_conductor, Y: Y_conductor})
) == 0

# The two roots of 3T^2-4zT+Y on the conductor are exchanged by this
# involution.
t_other = 4 * z / 3 - t
quadratic = 3 * t**2 - 4 * z * t + Y
assert sp.expand(
    quadratic.subs(t, t_other) - quadratic
) == 0

# A target monomial of total degree m and first-endpoint pole degree e
# has second-endpoint t exponent e+m.  Its scalar is simultaneously the
# top w coefficient of its first-endpoint coefficient.
alpha, beta, gamma = sp.symbols(
    "alpha beta gamma", integer=True, nonnegative=True
)
m = alpha + beta + gamma
e = 2 * alpha + beta - gamma
second_t_exponent = 3 * alpha + 2 * beta
assert sp.expand(second_t_exponent - (e + m)) == 0
first_top_scalar = (-1) ** alpha * (-3) ** beta
second_scalar = (-1) ** alpha * (-3) ** beta
assert first_top_scalar == second_scalar

# The same missing normalization root H controls both cusps.
H = 3 * c * t**2 - 2 * t - 3
P2 = sp.factor(((b + 1) ** 2 - 12 * a) / 9)
P3 = sp.factor(
    -sp.Rational(2, 3) * a * b
    + sp.Rational(1, 27) * b**3
    + 2 * a**2 * c
)
assert sp.expand(P2 - H**2 / 9) == 0

# At the first endpoint t=tau^-1, c=(2/3+w)tau, their leading forms are
# w^2 tau^-2 and w^3 tau^-3.
tau, w = sp.symbols("tau w")
first_substitution = {
    t: 1 / tau,
    c: (sp.Rational(2, 3) + w) * tau,
}
P2_first = sp.factor(P2.subs(first_substitution))
P3_first = sp.factor(P3.subs(first_substitution))
assert sp.limit(tau**2 * P2_first, tau, 0) == w**2
assert sp.limit(tau**3 * P3_first, tau, 0) == w**3

# At c=infinity their simultaneous leading forms are t^4 z^-2 and
# t^6 z^-3.  Products therefore realize every linked power n>=2.
P2_second = sp.factor(P2.subs(c, 1 / z))
P3_second = sp.factor(P3.subs(c, 1 / z))
assert sp.limit(z**2 * P2_second, z, 0) == t**4
assert sp.limit(z**3 * P3_second, z, 0) == t**6

# The square/cube pair is compatible leading data, not itself Darboux.
jacobian_P2_P3 = sp.factor(
    sp.diff(P2, t) * sp.diff(P3, c)
    - sp.diff(P2, c) * sp.diff(P3, t)
)
assert jacobian_P2_P3 == (
    sp.Rational(4, 27)
    * t**2
    * (3 * c * t**2 - 2 * t - 4)
    * H
)

# Their conductor restrictions are even Laurent polynomials in v, as
# required for genuine target-ring elements.
v = sp.symbols("v")
conductor_substitution = {
    c: v**2 / 9,
    t: 3 * (v + 2) / v**2,
}
assert sp.factor(P2.subs(conductor_substitution)) == 4 / v**2
assert sp.simplify(
    P3.subs(conductor_substitution)
    - (36 - v**2) / (27 * v**2)
) == 0

print("verified the exact second-endpoint Rees relation and conductor")
print("verified the linked square/cube cusp semigroup at both endpoints")
print("RESULT: TWO-CUSP PARITY ALONE DOES NOT REMOVE THE REDUCED SURVIVOR")
