#!/usr/bin/env python3
"""Exact checks for the quartic minimal-puncture monodromy obstruction."""

from __future__ import annotations

import itertools

import sympy as sp


t, u, x, y = sp.symbols("t u x y")


# The cubic critical-value identity used in the abstract dichotomy.
c, r, s = sp.symbols("c r s", nonzero=True)
z = sp.symbols("z")
derivative = 3 * c * (z - r) * (z - s)
primitive = sp.integrate(derivative, z)
critical_value_difference = sp.factor(
    primitive.subs(z, r) - primitive.subs(z, s)
)
assert critical_value_difference == -c * (r - s) ** 3 / 2


Permutation = tuple[int, int, int, int]
identity: Permutation = (0, 1, 2, 3)


def compose(first: Permutation, second: Permutation) -> Permutation:
    """Return first after second."""
    return tuple(first[second[index]] for index in range(4))


def generated_group(generators: tuple[Permutation, ...]) -> set[Permutation]:
    group = {identity}
    frontier = [identity]
    while frontier:
        current = frontier.pop()
        for generator in generators:
            for product in (
                compose(current, generator),
                compose(generator, current),
            ):
                if product not in group:
                    group.add(product)
                    frontier.append(product)
    return group


def orbit_partition(group: set[Permutation]) -> tuple[int, ...]:
    unseen = set(range(4))
    sizes: list[int] = []
    while unseen:
        seed = next(iter(unseen))
        orbit = {permutation[seed] for permutation in group}
        unseen -= orbit
        sizes.append(len(orbit))
    return tuple(sorted(sizes, reverse=True))


transpositions: list[Permutation] = []
for first in range(4):
    for second in range(first + 1, 4):
        permutation = list(identity)
        permutation[first], permutation[second] = (
            permutation[second],
            permutation[first],
        )
        transpositions.append(tuple(permutation))


# Any image generated by at most two smooth meridians is nontransitive.
for first, second in itertools.product(transpositions, repeat=2):
    partition = orbit_partition(generated_group((first, second)))
    assert partition in ((2, 1, 1), (2, 2), (3, 1))


# A local transposition image with orbit partition 2+1+1 is exactly C2,
# while disjoint transpositions give the prescribed 2+2 local image.
for first in transpositions:
    assert orbit_partition(generated_group((first,))) == (2, 1, 1)
for first, second in itertools.product(transpositions, repeat=2):
    group = generated_group((first, second))
    if orbit_partition(group) == (2, 2):
        assert compose(first, second) == compose(second, first)
        assert first != second
        assert len(group) == 4


# Exact quartic stress test: a non-full A2 cusp, one smooth vertical
# tangency, and two ordinary nodes.
p = t**2 - t**3
q = t**3 + t**4
implicit = -x**4 + 2 * x**3 + 10 * x**2 * y + 7 * x * y**2 + y**3 - 2 * y**2

assert sp.expand(implicit.subs({x: p, y: q})) == 0
assert sp.Poly(implicit, x, y).total_degree() == 4
assert sp.degree(implicit, y) == 3
assert sp.factor(sp.discriminant(implicit, y)) == (
    -x**3 * (27 * x - 4) * (x**2 - 4 * x - 4) ** 2
)

p_prime = sp.factor(sp.diff(p, t))
q_prime = sp.factor(sp.diff(q, t))
assert p_prime == -t * (3 * t - 2)
assert q_prime == t**2 * (4 * t + 3)
assert q_prime.subs(t, sp.Rational(2, 3)) != 0
assert sp.factor(p) == -t**2 * (t - 1)

# The only failure of immersion is the A2 cusp at t=0.
assert sp.gcd(sp.Poly(p_prime, t), sp.Poly(q_prime, t)).as_expr() == t

# Off-diagonal equal-image pairs give exactly two unordered pairs.
p_u = p.subs(t, u)
q_u = q.subs(t, u)
collision_p = sp.cancel((p - p_u) / (t - u))
collision_q = sp.cancel((q - q_u) / (t - u))
collision_resultant = sp.factor(sp.resultant(collision_p, collision_q, u))
assert collision_resultant == -t**2 * (t**4 - 2 * t**3 + 3 * t**2 + 2)
assert sp.discriminant(t**4 - 2 * t**3 + 3 * t**2 + 2, t) != 0

# Their image points are the two singularities cut out by the node factor.
node_x_polynomial = x**2 - 4 * x - 4
singular_points = sp.solve_poly_system(
    [
        implicit,
        sp.diff(implicit, x),
        sp.diff(implicit, y),
    ],
    x,
    y,
)
assert len(singular_points) == 3
assert (sp.Integer(0), sp.Integer(0)) in singular_points
for point_x, point_y in singular_points:
    if point_x != 0:
        assert sp.simplify(node_x_polynomial.subs(x, point_x)) == 0
        assert sp.simplify(point_y + 3 * point_x + 2) == 0

# The two nonzero singularities have nondegenerate quadratic tangent
# cones, hence are ordinary nodes.
hessian_determinant = sp.factor(sp.det(sp.hessian(implicit, (x, y))))
node_hessian = sp.Poly(
    hessian_determinant.subs(y, -3 * x - 2),
    x,
)
node_modulus = sp.Poly(node_x_polynomial, x)
assert sp.rem(node_hessian, node_modulus).as_expr() == 256 * x + 224
assert sp.resultant(256 * x + 224, node_x_polynomial, x) != 0

# At the origin the lowest terms are -2y^2+2x^3, and the
# normalization has orders (2,3), certifying an A2 cusp.
assert sp.Poly(p, t).terms()[-1][0] == (2,)
assert sp.Poly(q, t).terms()[-1][0] == (3,)
assert sp.Poly(implicit, x, y).coeff_monomial(y**2) == -2
assert sp.Poly(implicit, x, y).coeff_monomial(x**3) == 2

# Arithmetic genus three is exhausted by one cusp and two nodes;
# the degree pattern (3,4) gives a smooth unique point at infinity.
arithmetic_genus = (4 - 1) * (4 - 2) // 2
assert arithmetic_genus == 1 + 2


print("verified: the cubic has either one total or two simple critical points")
print("verified: two transpositions never act transitively on four sheets")
print("verified: 2+1+1 and 2+2 local images are nontransitive")
print("verified: the quartic stress test has a non-full cusp and two nodes")
print("RESULT: FOUR-PUNCTURED RATIONAL COORDINATE FIBERS ARE EXCLUDED")
