#!/usr/bin/env python3
"""Verify the conductor restriction map and monomial residue lattice.

This is an all-parameter symbolic check.  It does not assert that every
rational Darboux chart is monomial; it records the exact nonzero residue
coset for the full conductor-adapted monomial family.
"""

import sympy as sp


k = sp.symbols("k", integer=True)

# The rational canonical monomials are
#
#   Q=q^a*p^b,
#   P=(a-b)^-1*q^(1-a)*p^(1-b),
#
# with a=1+2k, b=1+3k.  The determinant of their exponent rows is a-b,
# so the displayed coefficient makes their Jacobian one.
a = 1 + 2 * k
b = 1 + 3 * k
c_exp = 1 - a
d_exp = 1 - b
exponent_determinant = sp.expand(a * d_exp - b * c_exp)
assert sp.simplify(exponent_determinant - (a - b)) == 0

# On the conductor q is proportional to v^3 and p to v^-2.  Thus Q has
# odd boundary weight one, while P has weight zero.
assert sp.expand(3 * a - 2 * b) == 1
assert sp.expand(3 * c_exp - 2 * d_exp) == 0

# In normalization coordinates Q is a constant times
#
#   v^(1+2k) c^(-k).
#
# After the quadratic quotient and the unique residue-correcting shear,
# the Liouville class has the following dlog(v),dlog(c) coefficients.
residue_v = sp.expand(sp.Rational(4, 3) * (1 + 2 * k))
residue_c = sp.expand(-sp.Rational(4, 3) * k - sp.Rational(2, 3))
lambda_kernel = sp.expand(sp.Rational(2, 3) * (2 * k + 1))

assert sp.simplify(residue_v - 2 * lambda_kernel) == 0
assert sp.simplify(residue_c + lambda_kernel) == 0

# Restriction to c=v^2/9 sends r_v*dlog(v)+r_c*dlog(c) to
# (r_v+2*r_c)*dlog(v).  The class is therefore invisible on the conductor.
assert sp.simplify(residue_v + 2 * residue_c) == 0

# The opposite boundary orientation Q|_C proportional to v^-1 has
# a=1+2k, b=2+3k.  Its residue-correcting shear has the opposite sign,
# but it lands in the same odd kernel lattice.
a_opposite = 1 + 2 * k
b_opposite = 2 + 3 * k
c_opposite = 1 - a_opposite
d_opposite = 1 - b_opposite
assert sp.expand(3 * a_opposite - 2 * b_opposite) == -1
assert sp.expand(3 * c_opposite - 2 * d_opposite) == 2

residue_v_opposite = sp.expand(
    -sp.Rational(4, 3) * (1 + 2 * k)
)
residue_c_opposite = sp.expand(
    -sp.Rational(2, 3) + sp.Rational(4, 3) * (1 + k)
)
lambda_opposite = sp.expand(-sp.Rational(2, 3) * (2 * k + 1))
assert sp.simplify(residue_v_opposite - 2 * lambda_opposite) == 0
assert sp.simplify(residue_c_opposite + lambda_opposite) == 0
assert sp.simplify(residue_v_opposite + 2 * residue_c_opposite) == 0

# Vanishing would require the forbidden half-integral exponent k=-1/2.
k_free = sp.symbols("k_free")
zero_solution = sp.solve(
    sp.Eq(sp.Rational(2, 3) * (2 * k_free + 1), 0), k_free
)
assert zero_solution == [-sp.Rational(1, 2)]
assert not zero_solution[0].is_integer

print("verified the conductor residue kernel generated by dlog(x/c)")
print("verified both monomial orientations have an odd nonzero dlog(x/c) class")
print("RESULT: BOTH ADAPTED MONOMIAL ORIENTATIONS HAVE A PARITY RESIDUE")
